#!/usr/bin/env python3
"""
Builds versions/manifest.json and history.html.

Two lists drive the panel and both live at the top of this file:

  FEEDBACK — every piece of direction received, quoted verbatim, with what was
             done about it and what is still open. Add a new entry at the TOP
             as feedback comes in; give it the next F-number.
  VERSIONS — the snapshots in versions/. Add after running pipeline/snapshot.sh.

Cross-linking is by id: a version lists the feedback ids it answers in
"answers", a feedback item lists the versions in "versions". The panel resolves
both directions, so you only have to be right once.

    python3 pipeline/build_history.py
"""
import io, json, os, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ===========================================================================
# STANDING CONSTRAINTS — project rules that apply to everything, not one-off
# feedback. Shown on the overview screen.
# ===========================================================================
CONSTRAINTS = [
 ("8px spacing system",
  "Every spacing value \u2014 padding, margin, gap, row and panel height, column width \u2014 is a multiple of 8, at every level of the design. 4px is a permitted half-step; type, 1px borders and radii are exempt. Written up in <code>DESIGN-RULES.md</code>."),
 ("Nothing shifts under the cursor",
  "Panel and column positions are constants; content scrolls inside its own box rather than growing it; scroll gutters are reserved."),
 ("No ambient motion",
  "Nothing drifts, floats or animates on its own. Transitions are colour and opacity only, on direct interaction."),
 ("No hallucination",
  "Every claim carries a credible reference with a link so it can be verified."),
 ("Quote, don't rephrase",
  "Summaries quote the source verbatim rather than paraphrasing it."),
 ("GoInvo style guide",
  "Sites follow <code>goinvo-style-guide.md</code>."),
]

# ===========================================================================
# FEEDBACK LEDGER — newest first
# ===========================================================================
FEEDBACK = [
 {
  "id": "F23",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Fixed height for the follow-up section; a click is a fill, not a dashed ring",
  "status": "addressed",
  "versions": ["v3.6"],
  "quote": "use this height as fixed default for what would follow it up section",
  "quotes": [
   "use this height as fixed default for what would follow it up section",
   "when mouse clicked, it shouldn\u2019t be the dashed line status, should be filled color no border status",
  ],
  "did": [
   ("Fixed default height", "addressed",
    "The section was sizing to its content, so the panel changed shape between concerns \u2014 2 families or 12 gave very different layouts. It now holds a fixed <b>384px</b> (8\u00d748) and scrolls inside, capped at 52% of the panel so a short window stays sane. Expanding still hands it the remaining space."),
   ("A click is a fill, not an outline", "addressed",
    "The dashed ring is a <i>keyboard</i> focus affordance and was appearing on mouse clicks too. Focus now records how it was moved: clicking gives the solid filled row with no border, arrow keys give the dashed ring. Verified both ways in both the map and the rail."),
  ],
  "open": None,
 },
 {
  "id": "F22",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Full names with constant padding, doubled quote mark, keyboard resumes from the last click",
  "status": "addressed",
  "versions": ["v3.5"],
  "quote": "show full name, put in rule, allow multiple rows if needed. each test will have the same paddings around regardless how many rows of the name it takes",
  "quotes": [
   "show full name, put in rule, allow multiple rows if needed. each test will have the same paddings around regardless how many rows of the name it takes",
   "remove the one additional quotation mark",
   "when using shortcuts on keyboard, esp arrow keys, start navigation based on where the last click was, not from default beginning",
  ],
  "did": [
   ("Full names on the map, never cut", "addressed",
    "Follow-up entries wrap to up to three lines instead of ending in an ellipsis. Zero truncated at every width tested."),
   ("Constant padding whatever the line count", "addressed",
    "Each entry carries exactly <b>8px above and below</b> whether its name takes one line or three \u2014 the row grows, the padding does not. Measured identical across a mixed one- and two-line block."),
   ("Written into the rules", "addressed",
    "<code>DESIGN-RULES.md</code> \u00a74 now states it: names are shown in full and wrap rather than truncate; padding is constant regardless of line count so rows in a list may legitimately differ in height; long lists are grouped rather than cut, with the true count on every header."),
   ("Doubled quotation mark", "addressed",
    "Descriptions arrive from the catalogue already wrapped in quotes and are rendered in a <code>&lt;q&gt;</code> element, which adds its own. The strip only handled straight quotes, so curly ones came through and doubled up. Now every flavour is stripped at build time."),
   ("Keyboard resumes from the last click", "addressed",
    "Clicking a marker, a concern, a follow-up test or a low/high toggle now moves the keyboard focus to that item, so the arrow keys carry on from where you were rather than restarting at the top of the first column."),
  ],
  "open": None,
 },
 {
  "id": "F21",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Group the long lists, dock the panels, 12px everywhere, full-row highlights",
  "status": "addressed",
  "versions": ["v3.4"],
  "quote": "any follow up more than 10 are too overwhelming, how can we simplify the guide without losing info?",
  "quotes": [
   "any follow up more than 10 are too overwhelming, how can we simplify the guide without losing info?",
   "fully left and right anchor the panels to reduce empty space, same as the bottom panel",
   "use only 12 px for all at same height",
   "the highlight should be the entire row, fix the framework to allow it, apply to all similar components",
  ],
  "did": [
   ("What the long tail actually is", "addressed",
    "23 of 47 concerns carry more than 40 markers. But <i>medication monitoring</i>, the worst at 378, has <b>372 of them in one family</b>, and by the catalogue's own ordering tier only <b>1</b> is commonly ordered against 117 specialist and 260 rarely ordered. The tail is not variety, it is obscure variants."),
   ("Grouped by family, commonly-ordered first", "addressed",
    "The list now opens as family headers carrying their <b>true</b> total, with only the commonly-ordered markers shown under each. Medication monitoring reads as <b>4 rows</b> instead of 378. Every family opens on click, and nothing is dropped \u2014 the counts state exactly what is behind each header."),
   ("Panels docked to the window edges", "addressed",
    "Rail, detail and footer sit flush to their edges with square outer corners; the 16px now lives only between a panel and the map, which hands the map back 32px of width and 32 of height."),
   ("12px, one size, one row height", "addressed",
    "Every label in every column is 12px Open Sans regular on a uniform row height. 12px holds from about 875px of window height upward; below that it steps down rather than letting rows collide, which is the only case where it is not exactly 12."),
   ("Full-row highlights", "addressed",
    "Rows now carry their own horizontal padding and cancel their container's with a negative margin, so a hover or a selection covers the whole row edge to edge. Applied to every row-like component \u2014 marker rows, follow-up rows, family headers and the why-list \u2014 not just the one that showed the problem."),
  ],
  "open": "The map's third column still draws individual markers rather than families; grouping it was agreed but is the next step.",
 },
 {
  "id": "F20",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Divider alignment, wrapped concern names, one type style",
  "status": "addressed",
  "versions": ["v3.3"],
  "quote": "use the same text style as the left column, tell me the size and typography",
  "quotes": [
   "align 29 with heart and cholesterol, use the same bottom spacing [what they can point at] has to [29 concerns no panel marker can reach]",
   "these names are still missing full name, put in multiple rows if needed",
   "use the same text style as the left column, tell me the size and typography",
  ],
  "did": [
   ("Divider aligned to the concern names", "addressed",
    "It was starting at the dot rather than the label, 21px left of <i>Heart &amp; cholesterol</i>. Both now start at the same x."),
   ("Same bottom spacing as a column header", "addressed",
    "Column headers sit 16px above their first row; the divider band now closes 16px after its last baseline, with the rule halfway through. Measured identical at every width."),
   ("Concern rows can be two lines", "addressed",
    "Row heights are no longer uniform \u2014 a name that will not fit on one line gets a taller row and the height is borrowed from the rest of the column. The wrapping decision always reserves room for the marker-count chip, so nothing reflows when you mark a marker."),
   ("Type and wrapping settled together", "addressed",
    "Narrowing the column makes more names wrap, which needs height, which can force the type down, which changes the wrapping again. Settled by iteration instead of a fixed multiplier, with a one-line truncated fallback if two lines cannot fit at the 8px floor \u2014 so rows can never run past the bottom of the map."),
   ("One type style across all three columns", "addressed",
    "Open Sans regular at a single size chosen per render from the tightest column budget \u2014 markers, concerns and follow-ups always match. State is carried by colour alone; the bold on live concerns and marked markers is gone, matching the rule already applied to the dots."),
  ],
  "open": None,
 },
 {
  "id": "F19",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Respect the side panels on a narrow screen",
  "status": "addressed",
  "versions": ["v3.2"],
  "quote": "when screen\u2019s smaller, respect the space taken by the side panels and show texts around it, the [complete blood count, comprehensive metabolic panel, and cholesterol lipid panel] are too close or covered by the panel right now, make them flexible to be on multiple rows as long as we keep same padding between panel and text always",
  "did": [
   ("The real cause", "addressed",
    "The map only subtracted the rail\u2019s width when the window was wider than 1080px \u2014 but the rail is <b>always</b> on screen; it is the detail panel and footer that get dropped. Below 1080 the marker column was being laid out from the window edge, so it ran under the rail."),
   ("Rail always counted", "addressed",
    "The left boundary now always allows for it, and the padding between any panel and the nearest text is a constant <b>16px</b> on every edge at every size. Verified from 860px to 2560px wide: the leftmost text never crosses the rail."),
   ("Sub-headers wrap", "addressed",
    "<i>Complete blood count</i>, <i>comprehensive metabolic panel</i> and <i>cholesterol / lipid panel</i> wrap to as many lines as the column needs \u2014 4 lines across the three groups at 1512px, 7 at 860px \u2014 instead of running under the panel."),
   ("Space they take is measured, not assumed", "addressed",
    "The header block height is computed from the wrapped line count, so the marker rows are laid out around it. Previously a fixed 15px was reserved regardless."),
  ],
  "open": None,
 },
 {
  "id": "F18",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Divider: more air on top, balanced, wrapping",
  "status": "addressed",
  "versions": ["v3.1"],
  "quote": "more space on top, align text with top and bottom, put in multiple rows if needed",
  "did": [
   ("It was running past the column", "addressed",
    "<i>29 concerns no panel marker can reach</i> was a single unwrapped line, so <i>can reach</i> fell off the right edge below about 1440px. It now wraps on word boundaries to fit the column \u2014 one line to 1440, two below that, never truncated."),
   ("Band sized from the content", "addressed",
    "Height is computed from the number of wrapped lines rather than fixed, so a two-line divider gets a taller band instead of crowding."),
   ("Space balanced top and bottom", "addressed",
    "24px above the first baseline and 16px below the rule \u2014 the extra 8 on top pays for the cap height, so the white space reads as equal. Measured: <b>~30px above, ~34px below</b>, against 21/21 before and a visibly tighter top."),
  ],
  "open": None,
 },
 {
  "id": "F17",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Marker column alignment, arrow gutter, and the divider as a header",
  "status": "addressed",
  "versions": ["v3.0"],
  "quote": "reserve space on the left of dot for arrow icons, right align all texts including the subheaders, put in multiple rows if needed",
  "quotes": [
   "reserve space on the left of dot for arrow icons, right align all texts including the subheaders, put in multiple rows if needed",
   "more space around this title, put in the same style as [what they can point at], remove the arrow",
  ],
  "did": [
   ("Arrow gets its own gutter", "addressed",
    "The \u25bc\u25b2 was appended to the label text, so marking a marker pushed its name left. It now sits in a reserved 16px slot between the label edge and the dot \u2014 verified that every label x is identical before and after marking."),
   ("One right edge for the whole column", "addressed",
    "Labels and the panel sub-headers (<i>complete blood count</i>, <i>comprehensive metabolic panel</i>, <i>cholesterol / lipid panel</i>) are all right-aligned to the same line, 24px left of the dot. The sub-headers were left-aligned against the opposite edge."),
   ("Wrapping where it is needed", "addressed",
    "Losing 24px to the gutter is absorbed by the existing word-wrap; no marker name is truncated down to 1280px, and only one is at 1200."),
   ("Divider reads as a section header", "addressed",
    "<i>29 concerns no panel marker can reach</i> now uses the same style as <i>what they can point at</i>, with the arrow dropped and the band opened from 17px to 55px \u2014 21px of clearance above the label and below the rule."),
  ],
  "open": None,
 },
 {
  "id": "F16",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Repeated recommendations, test drill-in, keyboard, full names, matching dots",
  "status": "addressed",
  "versions": ["v2.9"],
  "quote": "why would some returned content have bunch of repeated test recommendations?",
  "quotes": [
   "why would some returned content have bunch of repeated test recommendations?",
   "give keyboard shortcuts (arrow keys to go down up the list, left right the columns etc.) to navigate the page better",
   "click on each of them should lead to the curated right panel of the test details",
   "instead of not showing the rest name using [...], put full names on two rows if needed",
   "after clicking on a test, the right panel shows the test details while the test is highlighted under [would follow it up] with the rest content, not disappearing",
   "dots should be in the same size and style",
  ],
  "did": [
   ("The repeats were real, and were ours", "addressed",
    "LOINC carries one code per unit, specimen and method, so <i>Lead [Presence] in Blood</i>, <i>Lead [Mass/volume] in Blood</i> and <i>Lead [Moles/volume] in Blood</i> are three codes for one test. Truncating the name at the first bracket collapsed them into a list that read <i>Lead, Lead, Lead</i>. <b>41% of carried rows</b> were duplicate labels."),
   ("De-duplicated by analyte", "addressed",
    "Rows are grouped by the thing measured \u2014 bracket, trailing <i>in &lt;specimen&gt;</i> and <i>by &lt;method&gt;</i> all stripped, since LOINC often puts the specimen in bare text. Best-ranked row per analyte kept, the rest counted as a <code>\u00d7n</code> chip. Heavy metals: 53 rows \u2192 9 markers. Smoking: 21 \u2192 4."),
   ("Counts now say which is which", "addressed",
    "Headers and tooltips report distinct markers; the note reports both \u2014 <i>all 9 markers carried here &middot; from 53 LOINC rows</i>."),
   ("Keyboard navigation", "addressed",
    "\u2191\u2193 within a column, \u2190\u2192 between them, Home/End, Enter to select, L/N/H to mark the focused marker, X to add a concern, E to expand, R to reset, Esc to clear, ? for the shortcut sheet. Crossing columns follows the <b>edges</b>, not the row order: right from a marker lands on the first concern it points at, left from a concern lands on the first marker pointing at it."),
   ("Click a test for its own panel", "addressed",
    "Follow-ups are clickable from the list, the map and the keyboard. The panel shows what it measures with its source and verify link, any sourced relationship notes, and chips for every concern it is tagged to."),
   ("The list stays put", "addressed",
    "Selecting a test used to null the open concern, so the whole third column disappeared. The parent concern now stays open, the map keeps its rows, and the row highlights in place in the panel \u2014 including when it sits past the collapsed cut-off."),
   ("Full names over two rows", "addressed",
    "Labels wrap on word boundaries instead of truncating. The over-reserved right margin in the concern column was reclaimed, so every concern name now fits on one line down to 1366px wide. Type tightens when a follow-up wraps so both lines clear the 24px pitch."),
   ("One dot, everywhere", "addressed",
    "All four kinds of dot were different sizes. Now a single 5px radius across all three columns, with state carried by fill and stroke colour rather than geometry."),
  ],
  "open": "The file is 527\u2009KB, up from 230, because each carried marker now brings its description so the test panel has something to show.",
 },
 {
  "id": "F15",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Centre the low/norm/high labels over their pill segments",
  "status": "addressed",
  "versions": ["v2.8"],
  "quote": "align the low norm high to the center of each pill option",
  "did": [
   ("Found the offset", "addressed",
    "The header sat <b>8px right</b> of the pill it labels. The marker list reserves an 8px scrollbar gutter that the header, sitting outside the scroll area, does not \u2014 so identical 16px padding on both put them out of register."),
   ("Header padding corrected", "addressed",
    "Right padding 16 \u2192 24, matching the list\u2019s 8px gutter plus 8px row padding. Both columns now end at <code>panel &minus; 24</code>."),
   ("Each label centred on its own segment", "addressed",
    "The label row is a 3-column grid matching the pill\u2019s, with each label a block centred in its 24px cell rather than centred as one run of text."),
   ("Crowding fixed", "addressed",
    "<i>NORM</i> and <i>HIGH</i> were running together: 9px type with .06em tracking is ~22.4px in a 24px cell. Dropped to 8.5px with no tracking \u2014 20.4px, leaving clear gutters."),
  ],
  "open": None,
 },
 {
  "id": "F14",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Glyph pill, and anchor the follow-up list at the bottom",
  "status": "addressed",
  "versions": ["v2.7"],
  "quote": "since we have labels, no need to show words again in the pill, we can use other visual cues to indicate low and high, and save some space on pill design",
  "quotes": [
   "since we have labels, no need to show words again in the pill, we can use other visual cues to indicate low and high, and save some space on pill design",
   "always anchor this section in full (before expanding) at the bottom of the right panel",
  ],
  "did": [
   ("Words out of the pill", "addressed",
    "The column header already names the three states, so the segments carry a cue instead of a repeat: <b>\u25bc</b> \u2013 <b>\u25b2</b>. Position does the rest \u2014 left is low, right is high."),
   ("Glyphs match the map", "addressed",
    "\u25bc and \u25b2 are the same marks already used on flagged markers in the map, so the two views read the same way."),
   ("Pill narrowed 96px \u2192 72px", "addressed",
    "Three 24px segments. The 24px saved goes back to the marker-name column, which now fits <i>Aspartate aminotransferase</i> without truncating."),
   ("Follow-up list anchored to the bottom", "addressed",
    "<code>margin-top:auto</code> pins it to the foot of the panel, and it sizes to its content so all eight rows, the expander and the note show in full without scrolling."),
   ("Expanding flips it to the flexible section", "addressed",
    "Collapsed it is fixed-height and unscrolled; expanded to 40 it takes the remaining space and scrolls inside itself. The relationship notes above take whatever is left, with a 176px floor."),
   ("Note shortened to two lines", "addressed",
    "<i>8 drawn on the map \u00b7 top 40 of 386 carried here</i> over <i>tagged to this concern and ranked \u2014 not a confirmed diagnostic sequence</i>, so the honesty survives without eating the rows."),
   ("Still on the grid", "addressed",
    "72, 24, 8 and 4 throughout. Re-audited: zero off-grid spacing."),
  ],
  "open": None,
 },
 {
  "id": "F13",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Give the relationship notes more room by default",
  "status": "addressed",
  "versions": ["v2.6"],
  "quote": "give more space for this section by default",
  "did": [
   ("Section is no longer a fixed 184px box", "addressed",
    "\u201cHow these connect\u201d now flexes. It takes the larger share of whatever height is left after the header and the explanation \u2014 <code>flex:1.6</code> against <code>flex:1</code> for the follow-up list \u2014 with a 264px floor."),
   ("Two full notes visible by default", "addressed",
    "At a 880px-tall window the section clears roughly 300px, enough for two complete quote cards instead of one and a clipped second."),
   ("More air between cards", "addressed",
    "Card spacing 16px \u2192 24px, with the last card\u2019s margin removed so the section does not end on dead space."),
   ("Still on the grid", "addressed",
    "264, 160 and 24 are all multiples of 8. Re-audited: zero off-grid spacing."),
  ],
  "open": None,
 },
 {
  "id": "F12",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Detail panel padding, no scroll on \u201cwhy\u201d, expandable follow-ups, 8px everywhere",
  "status": "addressed",
  "versions": ["v2.5"],
  "quote": "apply 8px rule everywhere in every level of design. put that in rule and instruction",
  "quotes": [
   "fix the padding below [80 related markers] like the second img",
   "always fully reveal content under [why it is on the map], no scroll bar for that section",
   "need access to the rest [what would follow it up], make it an expandable section below maybe",
   "apply 8px rule everywhere in every level of design. put that in rule and instruction",
  ],
  "did": [
   ("Header no longer clips its subtitle", "addressed",
    "The detail header was a hard 78px box with mixed 13/15/11px padding, so \u201c80 related markers \u00b7 79 outside your panel\u201d was cut at the descender. Now 16px padding on a 96px minimum, vertically centred."),
   ("\u201cWhy it is on the map\u201d always reveals in full", "addressed",
    "The fixed 104px height and its scrollbar are gone \u2014 the section sizes to its content and is never clipped."),
   ("Follow-ups are expandable", "addressed",
    "The build now carries the top 40 per concern instead of 8. The panel shows 8 by default with <i>show all 40 carried here</i>, and states the true total: <i>the top 40 of 79 markers tagged to this concern outside your panel</i>. The map still draws 8. Expander resets when the selection changes."),
   ("8px applied at every level", "addressed",
    "Audited the whole stylesheet, not just the layout: header 56, footer 72, panel padding 16, section headers 16/16/8, list rows 32 and 8, chips 4/8, badges 4/8, legend swatches 8 with 8 gap, control height 24 with 8 padding. <b>Zero off-grid padding, margin, gap or height remain.</b>"),
   ("Written into the rules", "addressed",
    "<code>DESIGN-RULES.md</code> added at the project root: the 8px system with the reference values and a regex audit to run before shipping, plus the no-shift and no-motion rules and the sourcing rules. The three design rules also now head the standing-rules list on this panel\u2019s overview."),
  ],
  "open": None,
 },
 {
  "id": "F11",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Centre the follow-ups on the selected row; fix the pill",
  "status": "addressed",
  "versions": ["v2.4"],
  "quote": "why does content in [would follow it up] always starts mid page? shouldn\u2019t it be at top, or fix location of each test?",
  "quotes": [
   "why does content in [would follow it up] always starts mid page? shouldn\u2019t it be at top, or fix location of each test?",
   "also the contents in [would follow up] should be together and centered to the [what they can point at] selection row",
   "improve the pill, either show text in pill with comfortable padding (always follow 8px system as a rule), or simplify the pill with label on top the column",
  ],
  "did": [
   ("Cause of the mid-page start", "addressed",
    "The block was being centred in the <i>column</i>, not on anything meaningful \u2014 8 rows at 34px inside a 744px column lands a third of the way down. It looked arbitrary because it was."),
   ("Follow-ups are one block, centred on their concern row", "addressed",
    "The group is now anchored to the concern that produced it, so the fan of edges is symmetric about the connector dot. A short tick on the anchor row makes the alignment legible."),
   ("Row pitch tightened to 24px", "addressed",
    "A 32px pitch made the block 256px tall, which could not centre on any row in the top third without leaving the canvas. At 24px it centres exactly for every row below y\u202f\u2248\u202f130 and clamps gracefully above that."),
   ("Source badge dropped from the map", "addressed",
    "Two lines per row forced the block taller than it could be while staying centred. Quoted vs AI-written still appears on every row of the detail list, and in the tooltip."),
   ("Pill given real padding on an 8px grid", "addressed",
    "24px tall, 8px horizontal padding per segment, 96px column, 32px rows \u2014 all multiples of 8. The words <i>low</i> and <i>high</i> are no longer clipped."),
   ("Column header above the toggles", "addressed",
    "A non-scrolling header row labels the marker column and the three segments, so the pill reads without hovering. Took both options in the brief rather than one."),
   ("Rail widened to 320px", "addressed",
    "8\u00d740. Buys the room the padded pill needs without squeezing the marker names. The map's left boundary follows automatically."),
   ("8px audit across the rail", "addressed",
    "Gaps, paddings and chip spacing moved onto the grid: rail padding 16, group headers 16/8/8, chip gap 8, chip padding 4/8, footer 72."),
  ],
  "open": None,
 },
 {
  "id": "F10",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Connector dots on the right so lines clear the text",
  "status": "addressed",
  "versions": ["v2.3"],
  "quote": "I like it better. add another set of dots for connectors on the right side so the lines don't cover the text",
  "did": [
   ("Right-hand connector dot on every concern row", "addressed",
    "47 out-dots at the right edge of the concern column. Quiet grey by default, warm and filled on the row currently feeding the third column."),
   ("Follow-up edges leave from the out-dot", "addressed",
    "They used to start at the left-hand dot, which meant every curve swept right across the label it belonged to. Now they start clear of the longest label \u2014 at 1512\u00d7880 the out-dot sits at x\u202f927 while the longest label ends at x\u202f844."),
   ("Row now reads left to right", "addressed",
    "Incoming edge \u2192 left dot \u2192 label \u2192 marker count \u2192 right dot \u2192 outgoing edge. The two dots make the direction of flow legible on a single row."),
   ("Labels re-measured for the narrower column", "addressed",
    "Clip width reduced to leave room for the count and the out-dot. Zero label overlaps and zero overflow at six window sizes, and the out-dots verified clear of all label text at each."),
  ],
  "open": None,
 },
 {
  "id": "F9",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "No floating. Use the space.",
  "status": "addressed",
  "versions": ["v2.2"],
  "quote": "uhm, this is ridiculous, no floating around, and improve the space utility",
  "did": [
   ("All motion removed", "addressed",
    "The force simulation, the ambient drift and the animation loop are gone. Layout is a pure function of state and window size \u2014 same inputs, same pixels. Nothing moves unless you change something."),
   ("Circle replaced by columns", "addressed",
    "A radial layout inscribes a circle in a rectangle and wastes the corners. Three fixed columns \u2014 panel markers, concerns, follow-up tests \u2014 use the full width and height instead. <b>99\u2013100% of the height and 91\u201396% of the width</b> now carry content, up from 30\u201342%."),
   ("Every concern is legible", "addressed",
    "All 47 are readable rows with full labels, instead of unlabelled dots that only got a name when there was room. The 26 markers show full names rather than abbreviations."),
   ("Edges ordered to avoid crossings", "addressed",
    "Concerns are sorted by the average row of the markers pointing at them \u2014 barycentre ordering, the standard method in layered graph drawing \u2014 so the connecting curves mostly run flat."),
   ("The missing-data split is drawn", "addressed",
    "A divider separates the 18 concerns your panel can reach from the <b>29 it cannot</b>, labelled in place. The gap is now a visible feature of the layout rather than a sentence somewhere."),
   ("Type scales to the row", "addressed",
    "Font size is derived from row height and labels are clipped to their column, so a 1200\u00d7700 window degrades instead of colliding. Zero label overlaps and zero overflow measured at five window sizes."),
   ("Columns hold still", "addressed",
    "Column x positions are constants, so opening a concern does not shift anything already on screen \u2014 the guarantee from [[F7]] holds again, which the floating version had quietly broken."),
  ],
  "open": None,
 },
 {
  "id": "F8",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Make the map readable \u2014 let it float and spread",
  "status": "partial",
  "versions": ["v2.1"],
  "quote": "find a smarter way to make these readable, can be more spread out organically floating moving in the empty space, or other ways you see fitting",
  "did": [
   ("Fixed rings replaced by a force simulation", "addressed",
    "Nodes now float and settle where there is room. Three soft rules: a radial band per role, concerns pulled toward the markers that implicate them, and everything repelling everything. No node may enter a panel."),
   ("Dormant concerns get out of the way", "addressed",
    "The old ring gave all 47 concerns an equal slot whether or not they were in play. Now live concerns pull inward and grow; the other 44 drift to the edge as small dots. The crowding was structural, not cosmetic."),
   ("Labels are placed, not just drawn", "addressed",
    "Each frame, labels are sorted by importance and placed greedily \u2014 right, left, above, below \u2014 taking the first slot that collides with nothing already placed. A label that cannot fit is dropped rather than overlapped. Measured across four window sizes and every interaction state: <b>zero label collisions</b>."),
   ("Bands are elliptical, not circular", "addressed",
    "The free area between the panels is far wider than it is tall, so a circular layout left a third of the screen empty. Normalising into unit space and scaling back out fills the rectangle."),
   ("Ambient drift", "addressed",
    "Every node carries its own phase and breathes slowly even at rest, so the map reads as alive rather than as a diagram. Honoured <code>prefers-reduced-motion</code>."),
   ("Ripple made literal", "addressed",
    "Edges from a marker you have marked abnormal animate outward with a flowing dash, so the ripple travels rather than merely existing."),
   ("Panels still never move", "addressed",
    "The organic motion is confined to the map. Rails, detail slots and scroll gutters remain fixed."),
   ("The floating itself", "open",
    "Rejected on sight \u2014 see [[F9]]. Reading the brief as an invitation to build a physics simulation was the wrong call: drifting nodes make a diagram harder to read, not easier, and the radial form wasted the wide canvas. Replaced by a static column layout in v2.2."),
  ],
  "open": "The readability goal was right; the means were wrong. v2.1 is kept in the panel as the record of a direction that did not work.",
 },
 {
  "id": "F7",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "A different atlas: start from the annual panel and ripple outward",
  "status": "partial",
  "versions": ["v2.0"],
  "quote": "overall, the atlas should show the ripple effect of the abnormal findings user explore, not just data lists",
  "quotes": [
   "start with annual blood routine, show the potential concerns each/multiple markers can represent",
   "for each concern raised, click into it should what additional blood tests need to be done to confirm",
   "all interactions and panels and scroll bars are fixed and reserved space on screen, so any clicks and interaction user has won't shift content on screen",
   "when biomarkers relate to one another, contain little fun fact on how they relate across physiology etc.",
   "on top of what normal blood routine shows, user can add additional personal concerns of their health on another layer, which introduce more suggestions in blood works, related content might also reveal which tests have never been ordered but needed? which families of tests are incomplete? missing data is itself a clinical information to collect",
  ],
  "did": [
   ("Starts from the annual panel", "addressed",
    "All 26 markers of the CBC, CMP and lipid panel are the inner ring and the left rail. Each can be marked low or high; the ripple spreads from there."),
   ("Concerns each marker can represent", "addressed",
    "Derived from the catalogue's own concern tags: the 26 panel markers between them can raise <b>18 of 47</b> concerns. Calcium alone points at nine."),
   ("Click a concern for what would follow it up", "addressed",
    "Opening a concern fans its follow-up tests into an outer ring and lists them, ranked by how well sourced and how commonly ordered they are, each linking to its LOINC record."),
   ("Nothing shifts on interaction", "addressed",
    "Ring positions are computed once per window size and cached; every interaction changes colour and opacity only. All 47 concerns hold a permanent slot, so adding a personal concern moves nothing. Scroll areas use reserved gutters so a scrollbar never appears and nudges content."),
   ("Fun facts on how markers relate", "addressed",
    "<b>29 relationship notes</b>, each a verbatim quote from a MedlinePlus (NIH) page with a verify link \u2014 bilirubin coming from broken-down red cells, ALP living in both liver and bone, calcium riding on albumin, LDL being calculated rather than measured. All 29 were re-fetched and checked against their source pages: none altered, none missing."),
   ("Personal concern layer", "addressed",
    "The 29 concerns the annual panel cannot reach are addable as a second layer. Adding one that no panel marker touches says so plainly: <i>nothing in your routine bloodwork would reveal it</i>."),
   ("Missing data as clinical information", "addressed",
    "Marking one marker abnormal surfaces how many related tests sit outside the panel and have never been ordered. Across all 18 reachable concerns that is <b>3,399</b> tests."),
   ("A confirmed diagnostic sequence", "partial",
    "The follow-up lists are markers <b>tagged to a concern</b> in the catalogue, ranked \u2014 not a verified screen-then-confirm path. Only the 29 sourced notes and the 11 hand-authored conditions carry real sequencing. The panel says so rather than implying more."),
   ("Marker-to-marker network beyond the 29", "open",
    "Still blocked on the relationship layer from [[F1]]: 6 of 6,192 markers carry a cross-family link. The 29 notes are hand-curated, not a data model \u2014 they cover the annual panel and stop there."),
  ],
  "open": "The 29 relationship notes prove the idea but do not scale: they were researched one page at a time and cover only the 26 panel markers. Turning them into the <code>sets</code> and <code>edges</code> arrays scoped in \u00a75 of <code>INDEX-REFINEMENT.md</code> is what would let the ripple run past the annual panel into the rest of the catalogue.",
 },
 {
  "id": "F6",
  "date": "2026-07-30",
  "who": "Chloe",
  "title": "Track feedback in the history panel",
  "status": "addressed",
  "versions": [],
  "quote": "summarize all the feedbacks we have so far in history page as well, track them as they come in",
  "did": [
   ("Feedback ledger added to this panel", "addressed",
    "Every piece of direction so far, quoted verbatim, with what was done and what is still open."),
   ("Cross-linked to versions", "addressed",
    "Each feedback item links to the versions that answered it; each version lists the feedback it answers."),
   ("One place to add new items", "addressed",
    "The <code>FEEDBACK</code> list at the top of <code>pipeline/build_history.py</code>. Add an entry, re-run the script."),
  ],
  "open": None,
 },
 {
  "id": "F5",
  "date": "2026-07-30",
  "who": "Chloe",
  "title": "Fix the atlas panels in place",
  "status": "addressed",
  "versions": ["v1.1"],
  "quote": "let's workshop the atlas a bit more. I'd like every panel to be fixed on screen without collapsing or expanding movements, figure out the best placement for them, overlay is good too",
  "did": [
   ("Nothing scrolls or resizes", "addressed",
    "The stage is fixed; panels are absolutely positioned and hold their dimensions. Anything that could overflow scrolls inside its own box."),
   ("Placement resolved", "addressed",
    "Map as ground plane; controls top-left where reading starts, family index filling that column, detail opposite it on the right, legend and honesty line along the bottom."),
   ("Circles never jump", "addressed",
    "Positions pack once per stage size and cache; shade toggles only re-paint. Verified by diffing every circle's coordinates across a toggle."),
   ("Overlay for drill-in", "addressed",
    "Clicking through to a family's markers fades a sheet over the map. The layout underneath never moves."),
  ],
  "open": "The gap map still scrolls — you chose to workshop one screen first. Applying the same fixed language there is the obvious follow-on.",
 },
 {
  "id": "F4",
  "date": "2026-07-30",
  "who": "Chloe",
  "title": "Be explicit about what is actually live",
  "status": "addressed",
  "versions": ["v1.0"],
  "quote": "is the atlas version live on index?",
  "did": [
   ("Status is now stated, not implied", "addressed",
    "Versions carry live / candidate / superseded and the panel colours the timeline by it. The atlas is a candidate; <code>index.html</code> is still v0.4."),
   ("Rollback commands are status-aware", "addressed",
    "A candidate shows &ldquo;promote this version&rdquo; and points its git command at <code>index-v2.html</code>, where the file actually lives at that tag. Earlier versions point at <code>index.html</code>."),
  ],
  "open": None,
 },
 {
  "id": "F3",
  "date": "2026-07-30",
  "who": "Chloe",
  "title": "Version history with previews and rollback",
  "status": "addressed",
  "versions": ["v1.0"],
  "quote": "create a history record keeping panel for all the changes we have made, in case we need to roll back to older versions, make them previewable",
  "did": [
   ("Snapshots of every milestone", "addressed",
    "Six versions plus two reference artifacts in <code>versions/</code>, byte-for-byte copies verified against their git tags."),
   ("Previewable", "addressed",
    "Each renders live in an iframe as the real interactive build, with viewport toggles and open-full."),
   ("Rollback", "addressed",
    "Copy-the-snapshot and git-tag commands per version, plus a diff command to see what would change first."),
   ("Uncommitted work rescued", "addressed",
    "The free-text symptom search was sitting in the working tree; committed as its own tagged milestone (v0.4) so that state stays recoverable."),
  ],
  "open": "<code>versions/</code> is ~17 MB and will ride along on a Vercel deploy. That makes the panel shareable by URL, which seems worth it — say the word for a <code>.vercelignore</code>.",
 },
 {
  "id": "F2",
  "date": "2026-07-30",
  "who": "Chloe",
  "title": "Build the full scope, review before swapping",
  "status": "addressed",
  "versions": ["v1.0"],
  "quote": "implement the changes … Everything including R4 atlas … New file, review then swap",
  "did": [
   ("All seven recommendations built", "addressed",
    "R1&ndash;R7 including the full atlas screen. The 6,192-row table survives one level inside it."),
   ("Delivered for review, not swapped in", "addressed",
    "<code>index-v2.html</code> sits alongside the live site so it can be compared before promotion."),
  ],
  "open": None,
 },
 {
  "id": "F1",
  "date": "2026-07-30",
  "who": "Chloe",
  "title": "An atlas of blood, not another lab viewer",
  "status": "partial",
  "versions": ["v1.0", "v1.1"],
  "quote": "What we don't have is a model of the blood system itself. We don't know what other markers surround a result, what hasn't been measured, what should be measured next, or how biomarkers relate to one another across physiology.",
  "quotes": [
   "We already have good tools for seeing individual blood tests—and simple trends over time.",
   "Imagine a map instead of a list. Every blood marker exists within networks: inflammation, immunity, kidney function, metabolism, liver health, hormones, nutrition, coagulation, cancer, infection, genetics, and more. We need the “solar system” of blood markers, not isolated planets.",
   "The most valuable information may be what's missing. Which tests have never been ordered? Which families of tests are incomplete? … Missing data is itself clinical information.",
   "This is fundamentally a decision-space design problem.",
   "More data isn't the problem. Claude Shannon taught us that information reduces uncertainty. The challenge is designing interfaces that transform more information into better decisions instead of more confusion.",
   "The issue isn't the data itself. The problem is that we haven't designed an effective way for clinicians and patients to navigate it—to surface what's important, summarize the signals, expose the gaps, and reveal the relationships.",
   "The product isn't another lab viewer. It's a decision engine.",
   "The goal isn't simply to display blood work. It's to make the invisible structure of human physiology visible enough that clinicians and patients can ask better questions, order better tests, and make better decisions.",
  ],
  "did": [
   ("A map instead of a list", "addressed",
    "The atlas screen shows all 17 families as a packed map sized by what is inside them, replacing a landing page whose only promise was 6,192 rows."),
   ("Missing data as the headline", "addressed",
    "The hero leads with <b>26 of 6,192</b> &mdash; what a routine annual panel measures against what is measurable. The stat strip shows three gaps instead of three totals."),
   ("Which families are incomplete", "addressed",
    "The gap map takes what you have had drawn and returns per-family coverage. <b>14 of 17</b> families are untouched by a standard annual panel."),
   ("The six decision questions", "partial",
    "All six are on the landing as navigation, each honestly labelled. Two work; two are prototypes; one is evidenced for three panels only; one is not built."),
   ("Which tests belong together", "partial",
    "Only the three routine panels are modelled as sets. Nothing else in the catalogue is grouped by &ldquo;ordered together&rdquo;."),
   ("How biomarkers relate across physiology", "open",
    "Not built, and deliberately not faked. Only <b>6 of 6,192</b> markers carry a link to another family, so the map draws no edges and says so."),
   ("How one abnormal finding ripples", "open",
    "Blocked on the same missing relationship layer. The one worked example (iron-deficiency anemia) is hand-authored in <code>condition-lens.html</code>."),
   ("What should be measured next", "partial",
    "Screen-then-confirm exists as a prototype for one condition, not as a general capability."),
   ("Trends over time", "open",
    "Not built. Named as not built on the landing rather than quietly omitted."),
   ("What each biomarker means, with evidence", "partial",
    "All 6,192 carry a description and a link, but only <b>216</b> are quoted from a named authority; <b>5,976</b> were AI-written from the LOINC name. The ratio is on the front door."),
  ],
  "open": "The relationship layer is the blocker for three of the points above. The fix is two small additions alongside <code>tests</code> &mdash; a <code>sets</code> array for &ldquo;these are ordered together&rdquo; and an <code>edges</code> array for reflex links like low MCV &rarr; ferritin &mdash; each carrying its own quoted or reasoned source. Scoped in §5 of <code>INDEX-REFINEMENT.md</code>. Until it exists, any marker-level ripple view would be drawing edges that are not in the data.",
 },
]

# ===========================================================================
# VERSIONS — newest first
# ===========================================================================
VERSIONS = [
 {
  "id": "v3.6",
  "file": "v3.6-fixed-section.html",
  "title": "Ripple atlas \u2014 stable panel, click vs keyboard",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "candidate",
  "tag": "v3.6-fixed-section",
  "gitpath": "index-v3.html",
  "answers": ["F23"],
  "summary": "The follow-up section holds a fixed 384px so the panel keeps its shape between concerns, and a mouse click now gives a filled row rather than the keyboard focus ring.",
  "changes": [
   "<b>384px fixed default</b> for the follow-up section, scrolling inside, capped at 52% of the panel.",
   "<b>Dashed ring is keyboard-only</b> \u2014 clicking gives the solid fill with no border.",
   "Zero label overlaps at seven window sizes.",
  ],
 },
 {
  "id": "v3.5",
  "file": "v3.5-full-names.html",
  "title": "Ripple atlas \u2014 full names, constant padding",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v3.5-full-names",
  "gitpath": "index-v3.html",
  "answers": ["F22"],
  "summary": "Follow-up names wrap to up to three lines rather than truncating, with identical padding whatever the line count; the doubled quote mark is gone and the keyboard resumes from the last click.",
  "changes": [
   "<b>Full names, up to three lines</b>, zero truncated at every width tested.",
   "<b>8px above and below every entry</b> regardless of line count \u2014 the row grows, the padding does not.",
   "<b>Rule written down</b> in <code>DESIGN-RULES.md</code> \u00a74, along with the grouping rule for long lists.",
   "<b>Doubled quotation mark fixed</b> \u2014 curly quotes are now stripped at build time before the <code>&lt;q&gt;</code> element adds its own.",
   "<b>Keyboard focus follows the last click</b> instead of restarting at the top.",
  ],
 },
 {
  "id": "v3.4",
  "file": "v3.4-grouped-docked.html",
  "title": "Ripple atlas \u2014 grouped lists, docked panels",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v3.4-grouped-docked",
  "gitpath": "index-v3.html",
  "answers": ["F21"],
  "summary": "Follow-up lists group by family with the commonly-ordered markers shown first, panels dock to the window edges, one 12px type size, and highlights that cover the whole row.",
  "changes": [
   "<b>Family grouping</b> with true counts on each header; 378 markers read as 4 rows. Open a family for the rest.",
   "<b>Commonly-ordered first</b>, using the catalogue's own ordering tier.",
   "<b>Panels docked</b> flush to the window edges; 16px only between panel and map.",
   "<b>12px, uniform rows</b>, every column; steps down only below ~875px of window height.",
   "<b>Full-bleed row highlights</b> across every row-like component.",
   "Zero label overlaps at six window sizes; zero off-grid spacing.",
  ],
 },
 {
  "id": "v3.3",
  "file": "v3.3-type-system.html",
  "title": "Ripple atlas \u2014 one type system",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v3.3-type-system",
  "gitpath": "index-v3.html",
  "answers": ["F20"],
  "summary": "One text style across all three columns, concern rows that can take two lines, and the divider aligned to the names it sits among.",
  "changes": [
   "<b>Open Sans regular, one size per render</b>, shared by all three columns. State is colour only \u2014 no size or weight changes.",
   "<b>Variable concern row heights</b>: a name that needs two lines gets a taller row, borrowed from the rest of the column.",
   "<b>Type and wrapping fitted by iteration</b>, with a truncated single-line fallback so rows never overflow the map.",
   "<b>Divider aligned</b> to the concern labels, with the same 16px it would get from a column header.",
   "Zero label overlaps at six window sizes; nothing runs past the bottom.",
  ],
 },
 {
  "id": "v3.2",
  "file": "v3.2-narrow-safe.html",
  "title": "Ripple atlas \u2014 narrow-screen safe",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v3.2-narrow-safe",
  "gitpath": "index-v3.html",
  "answers": ["F19"],
  "summary": "The map no longer lays out under the left rail on a narrow window, and the panel sub-headers wrap to fit whatever width is left.",
  "changes": [
   "<b>The rail is always subtracted</b> from the map\u2019s width. It was only counted above 1080px, though the rail never hides \u2014 only the detail panel and footer do.",
   "<b>Constant 16px</b> between any panel and the nearest text, on every edge, at every size.",
   "<b>Sub-headers wrap to multiple lines</b>, and the space they need is measured from the wrapped result rather than a fixed reserve.",
   "Verified 860px to 2560px: no text crosses the rail, no ellipsis in the marker column, zero label overlaps.",
  ],
 },
 {
  "id": "v3.1",
  "file": "v3.1-divider-header.html",
  "title": "Ripple atlas \u2014 divider wraps and breathes",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v3.1-divider-header",
  "gitpath": "index-v3.html",
  "answers": ["F18"],
  "summary": "The unreachable-concerns divider wraps to fit its column and its band is sized from the content, with balanced space above and below.",
  "changes": [
   "<b>Wraps on word boundaries</b> \u2014 one line to 1440px, two below, never running past the column or truncated.",
   "<b>Band height computed from the line count</b> rather than fixed.",
   "<b>24px above the first baseline, 16px below the rule</b>, so the visual space reads as equal.",
   "Zero label overlaps at six window sizes; zero off-grid spacing.",
  ],
 },
 {
  "id": "v3.0",
  "file": "v3.0-marker-column.html",
  "title": "Ripple atlas \u2014 aligned marker column",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v3.0-marker-column",
  "gitpath": "index-v3.html",
  "answers": ["F17"],
  "summary": "The marker column gets one right edge, a reserved gutter for the low/high arrow, and the unreachable-concerns divider is restyled as a section header.",
  "changes": [
   "<b>16px arrow gutter</b> between the label edge and the dot, so marking a marker no longer shifts its name.",
   "<b>Labels and panel sub-headers share one right edge</b>, 24px left of the dot.",
   "<b>Divider restyled</b> to match the column headers, arrow removed, band opened 17px \u2192 55px.",
   "Zero label overlaps at six window sizes; zero off-grid spacing.",
  ],
 },
 {
  "id": "v2.9",
  "file": "v2.9-tests-and-keys.html",
  "title": "Ripple atlas \u2014 de-duplicated, drillable, keyboard-driven",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.9-tests-and-keys",
  "gitpath": "index-v3.html",
  "answers": ["F16"],
  "summary": "Follow-up lists de-duplicated by analyte, every test drillable into its own panel, full keyboard navigation, wrapped labels, and one dot size throughout.",
  "changes": [
   "<b>De-duplication by analyte</b> \u2014 53 LOINC rows become 9 markers with \u00d7n chips. 41% of rows were previously duplicate labels.",
   "<b>Test detail panel</b> reachable by click, map or keyboard: description, source, verify link, relationship notes, tagged concerns.",
   "<b>The follow-up list stays on screen</b> when a test is selected, with the row highlighted.",
   "<b>Keyboard</b>: arrows, Home/End, Enter, L/N/H, X, E, R, Esc, ?. Column changes follow the edges.",
   "<b>Labels wrap</b> rather than truncate; concern names fit on one line to 1366px.",
   "<b>One 5px dot</b> across all three columns; state is colour only.",
   "Zero label overlaps at six window sizes.",
  ],
  "note": "527 KB, up from 230, because each carried marker now brings its description.",
 },
 {
  "id": "v2.8",
  "file": "v2.8-pill-align.html",
  "title": "Ripple atlas \u2014 pill header aligned",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.8-pill-align",
  "gitpath": "index-v3.html",
  "answers": ["F15"],
  "summary": "The LOW / NORM / HIGH header now sits in register with the pill segments it labels.",
  "changes": [
   "<b>Header right padding 16 \u2192 24</b> to account for the scrollbar gutter the list reserves and the header does not.",
   "<b>Each label centred in its own 24px cell</b> via a matching 3-column grid.",
   "<b>8.5px, no tracking</b> so NORM and HIGH no longer touch.",
   "Zero off-grid spacing.",
  ],
 },
 {
  "id": "v2.7",
  "file": "v2.7-glyph-pill.html",
  "title": "Ripple atlas \u2014 glyph pill, anchored follow-ups",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.7-glyph-pill",
  "gitpath": "index-v3.html",
  "answers": ["F14"],
  "summary": "The low/normal/high pill drops its words for direction glyphs and narrows to 72px; the follow-up list pins to the bottom of the detail panel and shows its eight rows in full.",
  "changes": [
   "<b>Pill shows \u25bc \u2013 \u25b2</b> instead of repeating the words already in the column header. Same glyphs the map uses for flagged markers.",
   "<b>96px \u2192 72px</b>, the saved width returned to the marker names.",
   "<b>Follow-up list anchored to the panel foot</b> and sized to its content \u2014 eight rows, expander and note, no scrolling.",
   "<b>Expanding flips it</b> to the flexible, scrolling section; the notes above keep a 176px floor.",
   "Note compressed to two lines without losing the caveat.",
   "Zero off-grid spacing.",
  ],
 },
 {
  "id": "v2.6",
  "file": "v2.6-facts-space.html",
  "title": "Ripple atlas \u2014 roomier relationship notes",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.6-facts-space",
  "gitpath": "index-v3.html",
  "answers": ["F13"],
  "summary": "\u201cHow these connect\u201d gets the larger share of the detail panel instead of a fixed 184px box, so two full quote cards are visible by default.",
  "changes": [
   "<b>Relationship notes flex</b> at 1.6 against 1 for the follow-up list, with a 264px floor \u2014 they are the substance of the panel, so they get the space.",
   "<b>24px between cards</b>, last margin removed.",
   "Follow-up list keeps a 160px floor and its expander.",
   "Re-audited: zero off-grid spacing.",
  ],
 },
 {
  "id": "v2.5",
  "file": "v2.5-detail-8px.html",
  "title": "Ripple atlas \u2014 detail panel, 8px audit",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.5-detail-8px",
  "gitpath": "index-v3.html",
  "answers": ["F12"],
  "summary": "Detail panel rebuilt on the grid: nothing clipped in the header, the explanation section never scrolls, and the follow-up list expands to the rest.",
  "changes": [
   "<b>Header</b> \u2014 16px padding on a 96px minimum, vertically centred. The subtitle is no longer cut off.",
   "<b>\u201cWhy it is on the map\u201d sizes to its content</b> and has no scrollbar.",
   "<b>Follow-ups expand</b> \u2014 top 40 carried per concern (was 8), 8 shown by default, with the true total stated.",
   "<b>Full 8px audit</b> of the stylesheet: zero off-grid padding, margin, gap or height.",
   "<code>DESIGN-RULES.md</code> added, and the design rules now head the standing-rules list here.",
   "File grew 101\u2009KB \u2192 238\u2009KB carrying the extra follow-up rows.",
  ],
  "note": "Follow-up centring still clamps for concerns in the top ~130px, where a centred block would leave the canvas.",
 },
 {
  "id": "v2.4",
  "file": "v2.4-centred-followups.html",
  "title": "Ripple atlas \u2014 centred follow-ups, 8px pill",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.4-centred-followups",
  "gitpath": "index-v3.html",
  "answers": ["F11"],
  "summary": "Follow-up tests become one block centred on the concern row that produced them, and the low/normal/high pill is rebuilt on an 8px grid with a column header.",
  "changes": [
   "<b>Follow-ups centred on their concern row</b> at a 24px pitch, with a tick on the anchor row. They were previously centred in the column, which is why they started mid-page.",
   "<b>Pill rebuilt on the 8px system</b> \u2014 24px tall, 8px padding per segment, 96px column, 32px rows. No more clipped words.",
   "<b>Non-scrolling column header</b> labels the marker column and the three toggle segments.",
   "<b>Rail widened to 320px</b> (8\u00d740) so the padded pill does not squeeze the marker names.",
   "Source badge moved off the map into the detail list and tooltip, so each follow-up is one line and the block stays short enough to centre.",
   "Verified at six window sizes: zero label overlaps, zero overflow, out-dots clear of text, 92\u201396% width and 99\u2013100% height in use.",
  ],
  "note": "Centring clamps for concerns in the top ~130px, where a centred block would run off the canvas. Unavoidable; the anchor tick keeps the relationship readable.",
 },
 {
  "id": "v2.3",
  "file": "v2.3-right-connectors.html",
  "title": "Ripple atlas \u2014 right-side connectors",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.3-right-connectors",
  "gitpath": "index-v3.html",
  "answers": ["F10"],
  "summary": "Concern rows gain a second connector dot on their right edge, and the follow-up edges leave from there instead of sweeping back across the label text.",
  "changes": [
   "<b>47 right-hand connector dots</b>, one per concern row, at the right edge of the column.",
   "<b>Follow-up edges originate at the out-dot</b> rather than the left-hand dot, so no curve crosses a label.",
   "The out-dot is quiet grey until its row is the one feeding the third column, then warm and filled.",
   "Marker-count chip moved inboard to clear the new dot; label clip widths re-measured.",
   "Verified at six window sizes: zero label overlaps, zero overflow, out-dots clear of all text.",
  ],
  "note": "Only the concern column changed. Markers already had their dot on the outgoing side, and follow-up tests already had theirs on the incoming side.",
 },
 {
  "id": "v2.2",
  "file": "v2.2-column-atlas.html",
  "title": "Ripple atlas \u2014 three columns",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.2-column-atlas",
  "gitpath": "index-v3.html",
  "answers": ["F9"],
  "summary": "Static, deterministic, and dense: panel markers, concerns and follow-up tests as three fixed columns filling the whole canvas. No physics, no drift, no animation.",
  "changes": [
   "<b>Force simulation deleted.</b> Layout is a pure function of state and window size.",
   "<b>Three fixed columns</b> \u2014 26 panel markers grouped by CBC / CMP / lipid, all 47 concerns, and the follow-up tests for whichever concern is open.",
   "<b>Every row is labelled.</b> Full marker names, full concern names, no culling.",
   "<b>Barycentre ordering</b> puts each concern beside the markers that point at it, so edges run flat rather than crossing.",
   "<b>A drawn divider</b> separates the 18 concerns the annual panel can reach from the 29 it cannot.",
   "<b>Type scales with row height</b> and clips to its column: zero label overlaps and zero overflow at 1200\u00d7700 through 2560\u00d71400.",
   "Space used: 99\u2013100% of the height, 91\u201396% of the width.",
  ],
  "note": "Supersedes both v2.0 (fixed rings) and v2.1 (force layout). The rail, detail panel and the 29 sourced relationship notes are unchanged.",
 },
 {
  "id": "v2.1",
  "file": "v2.1-organic-ripple.html",
  "title": "Ripple atlas \u2014 organic layout",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.1-organic-ripple",
  "gitpath": "index-v3.html",
  "answers": ["F8"],
  "summary": "The ripple map stops being a fixed ring and becomes a live force simulation: nodes float, live concerns pull inward, dormant ones drift to the edge, and labels are placed only where they fit.",
  "changes": [
   "<b>Force simulation replaces the fixed rings.</b> A radial band per role, concerns sprung toward the markers that implicate them, universal repulsion, hard collision correction, and a boundary that keeps every node out of the panels.",
   "<b>Live concerns come forward, dormant ones recede.</b> The 47 concerns no longer each hold a permanent ring slot \u2014 the ones in play grow and move inward where there is room to label them.",
   "<b>Greedy label placement.</b> Labels are sorted by importance and take the first of four candidate positions that collides with nothing. Zero label overlaps at 1200\u00d7700 through 1920\u00d71080, in every interaction state.",
   "<b>Elliptical bands</b> so the layout fills a wide rectangle instead of inscribing a circle in it.",
   "<b>Ambient drift</b> \u2014 per-node phase, slow breathing motion, disabled under <code>prefers-reduced-motion</code>.",
   "<b>Flowing dash on live edges</b> so the ripple visibly travels outward from a marker you flag.",
   "Node overlaps: zero once settled, at every size tested.",
  ],
  "note": "Motion is confined to the map canvas. The rails, detail slots and scroll gutters stay fixed, so this does not undo the no-shift guarantee from v2.0.",
 },
 {
  "id": "v2.0",
  "file": "v2.0-ripple-atlas.html",
  "title": "Ripple atlas",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.0-ripple-atlas",
  "gitpath": "index-v3.html",
  "answers": ["F7"],
  "summary": "A different route into the atlas: start from the 26 markers of a routine annual panel, mark what came back abnormal, and watch the ripple spread into concerns and the tests that would follow them up.",
  "changes": [
   "<b>Three concentric rings.</b> Inner: the 26 annual-panel markers, grouped by CBC / CMP / lipid. Middle: all 47 concerns, each holding a permanent slot. Outer: the follow-up tests for whichever concern is open.",
   "<b>Mark low or high</b> on any panel marker and the concerns it can represent light up, with edges coloured by direction.",
   "<b>29 sourced relationship notes</b> \u2014 every one a verbatim MedlinePlus (NIH) quote with a verify link, re-checked against the source pages after authoring.",
   "<b>Personal concern layer.</b> The 29 concerns a routine panel cannot reach can be added by hand; one that no panel marker touches says so outright.",
   "<b>Nothing moves.</b> Ring geometry is computed once per window size and cached; interactions change colour and opacity only. Scroll areas reserve their gutters. Verified by diffing every circle coordinate across marking, selecting and adding.",
   "<b>Marker radius derived from the ring chord</b>, so the 26 inner circles cannot overlap at any window size. Checked at 1200\u00d7700 through 1920\u00d71080.",
   "95 KB standalone \u2014 no 6,192-row table, so it loads instantly.",
  ],
  "note": "This is an alternative to the v1.1 family atlas, not a replacement. v1.1 maps the whole catalogue by family; v2.0 starts from what you have actually had done. Both are candidates.",
 },
 {
  "id": "v1.1",
  "file": "v1.1-atlas-cockpit.html",
  "title": "Atlas cockpit — fixed panels",
  "date": "2026-07-30",
  "source": "index-v2.html",
  "status": "candidate",
  "tag": "v1.1-atlas-cockpit",
  "gitpath": "index-v2.html",
  "answers": ["F5"],
  "summary": "The atlas stops being a scrolling page and becomes a fixed cockpit: the map fills the viewport, everything else floats above it, nothing ever reflows.",
  "changes": [
   "<b>Nothing scrolls or resizes.</b> The stage is fixed; panels are absolutely positioned and hold their dimensions. Anything that could overflow scrolls inside its own box instead of growing.",
   "<b>Map is the ground plane.</b> It fills the viewport behind four floating glass panels — controls and family index on the left, detail on the right, legend and the honesty line along the bottom.",
   "<b>Circles never jump.</b> Positions are packed once per stage size and cached; toggling shade or re-ordering the index only re-paints colour. Verified by diffing circle coordinates across a shade toggle.",
   "<b>Packing is area-conserving</b> — circles scale to fill ~46% of whatever space the panels leave, so the map uses the room it has at any window size. Panel footprints are measured, not guessed, so no circle hides under a panel.",
   "<b>Detail panel is always mounted</b> at a fixed size. With nothing selected it shows the whole-atlas summary; selecting a family swaps the content without changing the box.",
   "<b>Drill-in is an overlay sheet</b> that fades over the map — every marker in the family, filterable, each linking to its LOINC record. Esc or the scrim closes it.",
   "Index and map cross-highlight on hover; clicking either selects, clicking again deselects.",
   "<b>No dimming of unselected families.</b> The shape of what is unmeasured is the point of the map, so it stays readable while you inspect one family.",
  ],
  "note": "The family-card grid from v1.0 is gone — the index rail and detail panel replace it. Landing and gap map are unchanged.",
 },
 {
  "id": "v1.0",
  "file": "v1.0-atlas-rebuild.html",
  "title": "Atlas rebuild",
  "date": "2026-07-30",
  "source": "index-v2.html",
  "status": "superseded",
  "tag": "v1.0-atlas",
  "gitpath": "index-v2.html",
  "answers": ["F1", "F2", "F3", "F4"],
  "summary": "Landing reframed from a navigation question into a claim, plus two new screens: a gap map and a family atlas.",
  "changes": [
   "<b>Hero states the thesis.</b> “Where do you want to start?” becomes “There are 6,192 things that can be measured in your blood. A routine annual checkup measures 26.”",
   "<b>Stat strip shows gaps, not totals.</b> The volume pair (6,192 tests · 17 body systems) is replaced by 26 of 6,192 in a routine panel, 1,602 markers no symptom reaches, and 4 of 17 families with no quoted source.",
   "<b>New gap map</b> (<code>#cxGaps</code>) — mark the panels you’ve had, search in individual markers, see per-family coverage. Persists to <code>localStorage</code>.",
   "<b>New family atlas</b> (<code>#cxAtlas</code>) — 17 family cards, shade by routine-panel or source coverage, sort by size / least covered / A–Z.",
   "<b>Six-question spine</b> on the landing, each labelled built / prototype / partial / not built.",
   "<b>Family map generated from the payload</b> by deterministic circle packing. No edges drawn, because only 6 of 6,192 markers carry a link to another family.",
   "<b>Honesty band</b> — 216 quoted entries vs 5,976 AI-written, with source names read out of the data.",
   "Fixed two bugs found in testing: <code>[].slice.call()</code> on a <code>Set</code> returns empty, which had silently broken the added-markers list and localStorage persistence.",
  ],
  "note": "Every figure is computed from the payload at load, so the copy cannot drift from the dataset. Regenerate with <code>pipeline/build_v2.py</code>.",
 },
 {
  "id": "v0.4",
  "file": "v0.4-symptom-search.html",
  "title": "Free-text symptom search",
  "date": "2026-07-30",
  "source": "index.html (working tree)",
  "status": "live",
  "tag": "v0.4-symptom-search",
  "answers": [],
  "diff": "196 added, 18 removed",
  "summary": "The last state of the original dashboard before the atlas rebuild. This is the roll-back target if the atlas goes wrong.",
  "changes": [
   "Free-text search on the condition explorer home (<code>cxFeelSearch</code>) with fuzzy matching into concern chips.",
   "“Search all tests” escape hatch from the search results into the table view.",
   "Feedback link added to the dashboard header.",
   "Blood-fill animation on the landing figure retuned (<code>cxrise</code> 120px → 185px).",
  ],
  "note": "These edits were uncommitted when the atlas work began; committed as their own milestone so this exact state stays recoverable.",
 },
 {
  "id": "v0.3",
  "file": "v0.3-polished-landing.html",
  "title": "Polished landing and table toolbar",
  "date": "2026-07-29",
  "ref": "2f8f5ec",
  "source": "commit 2f8f5ec",
  "tag": "v0.3-polish",
  "answers": [],
  "diff": "250 added, 25 removed",
  "summary": "Visual pass on the two-door landing and usability work on the all-tests table.",
  "changes": [
   "Landing figure with the blood-fill mask, animated leader lines to each route card, and live card stats read from the dataset.",
   "Per-system mini bar chart on the “Explore all tests” card.",
   "Table toolbar: expand all, collapse all, back to top, and a sticky toolbar dock.",
   "Rollup system bar with legend in the dashboard header.",
  ],
 },
 {
  "id": "v0.2",
  "file": "v0.2-condition-explorer.html",
  "title": "Condition explorer prototype",
  "date": "2026-07-23",
  "ref": "1f7acac",
  "source": "commit 1f7acac",
  "tag": "v0.2-condition-explorer",
  "answers": [],
  "diff": "3,595 added, 81 removed",
  "summary": "The biggest single change in the project's history: conditions become a first-class object sitting between symptoms and tests.",
  "changes": [
   "Route landing (<code>#cxRoute</code>) with two doors — start from how you feel, or explore all tests.",
   "Condition explorer (<code>#cxApp</code>): symptom → candidate conditions → condition lens.",
   "Condition lens with ripple diagram, “have you had this?” checklist, path-to-diagnosis track and a locked miniDx card.",
   "All-tests table view with name / system / source filters.",
   "Added <code>condition-lens.html</code>, <code>IMPROVEMENT-PLAN.md</code> and the <code>pipeline/</code> source files.",
  ],
  "note": "This is the version <code>IMPROVEMENT-PLAN.md</code> was written against.",
 },
 {
  "id": "v0.1",
  "file": "v0.1-initial-dashboard.html",
  "title": "Initial dashboard",
  "date": "2026-07-22",
  "ref": "786bfc5",
  "source": "commit 786bfc5",
  "tag": "v0.1-initial",
  "answers": [],
  "diff": "1,024 added",
  "summary": "The original concern-in, test-list-out tool. No conditions, no landing page, no table view.",
  "changes": [
   "6,192-test catalogue with the concern picker and age / sex / life-stage / medication filters.",
   "Rollup stat strip and callouts.",
   "“Worth asking your doctor about” ranking, and annual-panel coverage against what sits outside it.",
   "Source-quoted vs AI-generated badges throughout.",
  ],
 },
]

REFS = [
 {
  "id": "ref-wireframe",
  "file": "ref-atlas-wireframe.html",
  "title": "Atlas landing wireframe (annotated)",
  "date": "2026-07-29",
  "summary": "The annotated mockup v1.0 was built from. Each block carries a margin note explaining what changed and why. Read alongside INDEX-REFINEMENT.md.",
 },
 {
  "id": "ref-lens",
  "file": "ref-condition-lens.html",
  "title": "Condition lens — iron-deficiency anemia",
  "date": "2026-07-23",
  "summary": "Standalone, hand-authored prototype of one condition worked end to end: ripple, coverage, path to diagnosis, miniDx. The reference build the explorer was modelled on.",
 },
]

# ===========================================================================
def fsize(p):
    try:
        return round(os.path.getsize(p) / 1048576.0, 2)
    except OSError:
        return None

for v in VERSIONS + REFS:
    v["mb"] = fsize(os.path.join(ROOT, "versions", v["file"]))
    if v["mb"] is None:
        raise SystemExit("missing snapshot: versions/" + v["file"])

# resolve feedback -> versions from the versions' own "answers", so the two
# lists cannot disagree
for f in FEEDBACK:
    linked = [v["id"] for v in VERSIONS if f["id"] in v.get("answers", [])]
    f["versions"] = sorted(set(f.get("versions", []) + linked), reverse=True)

manifest = {
    "generated": subprocess.run(["date", "-u", "+%Y-%m-%dT%H:%M:%SZ"],
                                capture_output=True, text=True).stdout.strip(),
    "live": "index.html",
    "constraints": CONSTRAINTS,
    "feedback": FEEDBACK,
    "versions": VERSIONS,
    "references": REFS,
}
io.open(os.path.join(ROOT, "versions", "manifest.json"), "w", encoding="utf8").write(
    json.dumps(manifest, indent=1, ensure_ascii=False))

TOTAL_MB = round(sum(v["mb"] for v in VERSIONS + REFS), 1)
COUNTS = {k: sum(1 for f in FEEDBACK if f["status"] == k)
          for k in ("addressed", "partial", "open")}

HTML = io.open(os.path.join(ROOT, "pipeline", "history_template.html"),
               encoding="utf8").read()
HTML = HTML.replace("__MANIFEST__", json.dumps(manifest, ensure_ascii=False))
HTML = HTML.replace("__TOTAL__", str(TOTAL_MB))
io.open(os.path.join(ROOT, "history.html"), "w", encoding="utf8").write(HTML)

print("versions/manifest.json  %d feedback, %d versions, %d references"
      % (len(FEEDBACK), len(VERSIONS), len(REFS)))
print("history.html            %.1f KB, %.1f MB of snapshots indexed"
      % (len(HTML) / 1024.0, TOTAL_MB))
print("feedback                %(addressed)d addressed, %(partial)d partial, %(open)d open" % COUNTS)
for f in FEEDBACK:
    print("   %-3s %-9s %-44s -> %s" % (f["id"], f["status"], f["title"],
                                        ", ".join(f["versions"]) or "—"))
