#!/usr/bin/env python3
"""
Builds versions/manifest.json and history.html.

Two lists drive the panel and both live at the top of this file:

  FEEDBACK — every piece of direction received, quoted verbatim, with what was
             done about it and what is still open. Add a new entry at the TOP
             as feedback comes in; give it the next F-number.
  VERSIONS — the snapshots in versions/. Add after running pipeline/snapshot.sh.

Cross-linking is by id: a version lists the feedback ids it answers in
"answers", a feedback item lists the versions in "versions". The panel resolves
both directions, so you only have to be right once.

    python3 pipeline/build_history.py
"""
import io, json, os, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ===========================================================================
# STANDING CONSTRAINTS — project rules that apply to everything, not one-off
# feedback. Shown on the overview screen.
# ===========================================================================
CONSTRAINTS = [
 ("8px spacing system",
  "Every spacing value \u2014 padding, margin, gap, row and panel height, column width \u2014 is a multiple of 8, at every level of the design. 4px is a permitted half-step; type, 1px borders and radii are exempt. Written up in <code>DESIGN-RULES.md</code>."),
 ("Nothing shifts under the cursor",
  "Panel and column positions are constants; content scrolls inside its own box rather than growing it; scroll gutters are reserved."),
 ("No ambient motion",
  "Nothing drifts, floats or animates on its own. Transitions are colour and opacity only, on direct interaction."),
 ("No hallucination",
  "Every claim carries a credible reference with a link so it can be verified."),
 ("Quote, don't rephrase",
  "Summaries quote the source verbatim rather than paraphrasing it."),
 ("GoInvo style guide",
  "Sites follow <code>goinvo-style-guide.md</code>."),
]

# ===========================================================================
# FEEDBACK LEDGER — newest first
# ===========================================================================
FEEDBACK = [
 {
  "id": "F13",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Give the relationship notes more room by default",
  "status": "addressed",
  "versions": ["v2.6"],
  "quote": "give more space for this section by default",
  "did": [
   ("Section is no longer a fixed 184px box", "addressed",
    "\u201cHow these connect\u201d now flexes. It takes the larger share of whatever height is left after the header and the explanation \u2014 <code>flex:1.6</code> against <code>flex:1</code> for the follow-up list \u2014 with a 264px floor."),
   ("Two full notes visible by default", "addressed",
    "At a 880px-tall window the section clears roughly 300px, enough for two complete quote cards instead of one and a clipped second."),
   ("More air between cards", "addressed",
    "Card spacing 16px \u2192 24px, with the last card\u2019s margin removed so the section does not end on dead space."),
   ("Still on the grid", "addressed",
    "264, 160 and 24 are all multiples of 8. Re-audited: zero off-grid spacing."),
  ],
  "open": None,
 },
 {
  "id": "F12",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Detail panel padding, no scroll on \u201cwhy\u201d, expandable follow-ups, 8px everywhere",
  "status": "addressed",
  "versions": ["v2.5"],
  "quote": "apply 8px rule everywhere in every level of design. put that in rule and instruction",
  "quotes": [
   "fix the padding below [80 related markers] like the second img",
   "always fully reveal content under [why it is on the map], no scroll bar for that section",
   "need access to the rest [what would follow it up], make it an expandable section below maybe",
   "apply 8px rule everywhere in every level of design. put that in rule and instruction",
  ],
  "did": [
   ("Header no longer clips its subtitle", "addressed",
    "The detail header was a hard 78px box with mixed 13/15/11px padding, so \u201c80 related markers \u00b7 79 outside your panel\u201d was cut at the descender. Now 16px padding on a 96px minimum, vertically centred."),
   ("\u201cWhy it is on the map\u201d always reveals in full", "addressed",
    "The fixed 104px height and its scrollbar are gone \u2014 the section sizes to its content and is never clipped."),
   ("Follow-ups are expandable", "addressed",
    "The build now carries the top 40 per concern instead of 8. The panel shows 8 by default with <i>show all 40 carried here</i>, and states the true total: <i>the top 40 of 79 markers tagged to this concern outside your panel</i>. The map still draws 8. Expander resets when the selection changes."),
   ("8px applied at every level", "addressed",
    "Audited the whole stylesheet, not just the layout: header 56, footer 72, panel padding 16, section headers 16/16/8, list rows 32 and 8, chips 4/8, badges 4/8, legend swatches 8 with 8 gap, control height 24 with 8 padding. <b>Zero off-grid padding, margin, gap or height remain.</b>"),
   ("Written into the rules", "addressed",
    "<code>DESIGN-RULES.md</code> added at the project root: the 8px system with the reference values and a regex audit to run before shipping, plus the no-shift and no-motion rules and the sourcing rules. The three design rules also now head the standing-rules list on this panel\u2019s overview."),
  ],
  "open": None,
 },
 {
  "id": "F11",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Centre the follow-ups on the selected row; fix the pill",
  "status": "addressed",
  "versions": ["v2.4"],
  "quote": "why does content in [would follow it up] always starts mid page? shouldn\u2019t it be at top, or fix location of each test?",
  "quotes": [
   "why does content in [would follow it up] always starts mid page? shouldn\u2019t it be at top, or fix location of each test?",
   "also the contents in [would follow up] should be together and centered to the [what they can point at] selection row",
   "improve the pill, either show text in pill with comfortable padding (always follow 8px system as a rule), or simplify the pill with label on top the column",
  ],
  "did": [
   ("Cause of the mid-page start", "addressed",
    "The block was being centred in the <i>column</i>, not on anything meaningful \u2014 8 rows at 34px inside a 744px column lands a third of the way down. It looked arbitrary because it was."),
   ("Follow-ups are one block, centred on their concern row", "addressed",
    "The group is now anchored to the concern that produced it, so the fan of edges is symmetric about the connector dot. A short tick on the anchor row makes the alignment legible."),
   ("Row pitch tightened to 24px", "addressed",
    "A 32px pitch made the block 256px tall, which could not centre on any row in the top third without leaving the canvas. At 24px it centres exactly for every row below y\u202f\u2248\u202f130 and clamps gracefully above that."),
   ("Source badge dropped from the map", "addressed",
    "Two lines per row forced the block taller than it could be while staying centred. Quoted vs AI-written still appears on every row of the detail list, and in the tooltip."),
   ("Pill given real padding on an 8px grid", "addressed",
    "24px tall, 8px horizontal padding per segment, 96px column, 32px rows \u2014 all multiples of 8. The words <i>low</i> and <i>high</i> are no longer clipped."),
   ("Column header above the toggles", "addressed",
    "A non-scrolling header row labels the marker column and the three segments, so the pill reads without hovering. Took both options in the brief rather than one."),
   ("Rail widened to 320px", "addressed",
    "8\u00d740. Buys the room the padded pill needs without squeezing the marker names. The map's left boundary follows automatically."),
   ("8px audit across the rail", "addressed",
    "Gaps, paddings and chip spacing moved onto the grid: rail padding 16, group headers 16/8/8, chip gap 8, chip padding 4/8, footer 72."),
  ],
  "open": None,
 },
 {
  "id": "F10",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Connector dots on the right so lines clear the text",
  "status": "addressed",
  "versions": ["v2.3"],
  "quote": "I like it better. add another set of dots for connectors on the right side so the lines don't cover the text",
  "did": [
   ("Right-hand connector dot on every concern row", "addressed",
    "47 out-dots at the right edge of the concern column. Quiet grey by default, warm and filled on the row currently feeding the third column."),
   ("Follow-up edges leave from the out-dot", "addressed",
    "They used to start at the left-hand dot, which meant every curve swept right across the label it belonged to. Now they start clear of the longest label \u2014 at 1512\u00d7880 the out-dot sits at x\u202f927 while the longest label ends at x\u202f844."),
   ("Row now reads left to right", "addressed",
    "Incoming edge \u2192 left dot \u2192 label \u2192 marker count \u2192 right dot \u2192 outgoing edge. The two dots make the direction of flow legible on a single row."),
   ("Labels re-measured for the narrower column", "addressed",
    "Clip width reduced to leave room for the count and the out-dot. Zero label overlaps and zero overflow at six window sizes, and the out-dots verified clear of all label text at each."),
  ],
  "open": None,
 },
 {
  "id": "F9",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "No floating. Use the space.",
  "status": "addressed",
  "versions": ["v2.2"],
  "quote": "uhm, this is ridiculous, no floating around, and improve the space utility",
  "did": [
   ("All motion removed", "addressed",
    "The force simulation, the ambient drift and the animation loop are gone. Layout is a pure function of state and window size \u2014 same inputs, same pixels. Nothing moves unless you change something."),
   ("Circle replaced by columns", "addressed",
    "A radial layout inscribes a circle in a rectangle and wastes the corners. Three fixed columns \u2014 panel markers, concerns, follow-up tests \u2014 use the full width and height instead. <b>99\u2013100% of the height and 91\u201396% of the width</b> now carry content, up from 30\u201342%."),
   ("Every concern is legible", "addressed",
    "All 47 are readable rows with full labels, instead of unlabelled dots that only got a name when there was room. The 26 markers show full names rather than abbreviations."),
   ("Edges ordered to avoid crossings", "addressed",
    "Concerns are sorted by the average row of the markers pointing at them \u2014 barycentre ordering, the standard method in layered graph drawing \u2014 so the connecting curves mostly run flat."),
   ("The missing-data split is drawn", "addressed",
    "A divider separates the 18 concerns your panel can reach from the <b>29 it cannot</b>, labelled in place. The gap is now a visible feature of the layout rather than a sentence somewhere."),
   ("Type scales to the row", "addressed",
    "Font size is derived from row height and labels are clipped to their column, so a 1200\u00d7700 window degrades instead of colliding. Zero label overlaps and zero overflow measured at five window sizes."),
   ("Columns hold still", "addressed",
    "Column x positions are constants, so opening a concern does not shift anything already on screen \u2014 the guarantee from [[F7]] holds again, which the floating version had quietly broken."),
  ],
  "open": None,
 },
 {
  "id": "F8",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "Make the map readable \u2014 let it float and spread",
  "status": "partial",
  "versions": ["v2.1"],
  "quote": "find a smarter way to make these readable, can be more spread out organically floating moving in the empty space, or other ways you see fitting",
  "did": [
   ("Fixed rings replaced by a force simulation", "addressed",
    "Nodes now float and settle where there is room. Three soft rules: a radial band per role, concerns pulled toward the markers that implicate them, and everything repelling everything. No node may enter a panel."),
   ("Dormant concerns get out of the way", "addressed",
    "The old ring gave all 47 concerns an equal slot whether or not they were in play. Now live concerns pull inward and grow; the other 44 drift to the edge as small dots. The crowding was structural, not cosmetic."),
   ("Labels are placed, not just drawn", "addressed",
    "Each frame, labels are sorted by importance and placed greedily \u2014 right, left, above, below \u2014 taking the first slot that collides with nothing already placed. A label that cannot fit is dropped rather than overlapped. Measured across four window sizes and every interaction state: <b>zero label collisions</b>."),
   ("Bands are elliptical, not circular", "addressed",
    "The free area between the panels is far wider than it is tall, so a circular layout left a third of the screen empty. Normalising into unit space and scaling back out fills the rectangle."),
   ("Ambient drift", "addressed",
    "Every node carries its own phase and breathes slowly even at rest, so the map reads as alive rather than as a diagram. Honoured <code>prefers-reduced-motion</code>."),
   ("Ripple made literal", "addressed",
    "Edges from a marker you have marked abnormal animate outward with a flowing dash, so the ripple travels rather than merely existing."),
   ("Panels still never move", "addressed",
    "The organic motion is confined to the map. Rails, detail slots and scroll gutters remain fixed."),
   ("The floating itself", "open",
    "Rejected on sight \u2014 see [[F9]]. Reading the brief as an invitation to build a physics simulation was the wrong call: drifting nodes make a diagram harder to read, not easier, and the radial form wasted the wide canvas. Replaced by a static column layout in v2.2."),
  ],
  "open": "The readability goal was right; the means were wrong. v2.1 is kept in the panel as the record of a direction that did not work.",
 },
 {
  "id": "F7",
  "date": "2026-07-31",
  "who": "Chloe",
  "title": "A different atlas: start from the annual panel and ripple outward",
  "status": "partial",
  "versions": ["v2.0"],
  "quote": "overall, the atlas should show the ripple effect of the abnormal findings user explore, not just data lists",
  "quotes": [
   "start with annual blood routine, show the potential concerns each/multiple markers can represent",
   "for each concern raised, click into it should what additional blood tests need to be done to confirm",
   "all interactions and panels and scroll bars are fixed and reserved space on screen, so any clicks and interaction user has won't shift content on screen",
   "when biomarkers relate to one another, contain little fun fact on how they relate across physiology etc.",
   "on top of what normal blood routine shows, user can add additional personal concerns of their health on another layer, which introduce more suggestions in blood works, related content might also reveal which tests have never been ordered but needed? which families of tests are incomplete? missing data is itself a clinical information to collect",
  ],
  "did": [
   ("Starts from the annual panel", "addressed",
    "All 26 markers of the CBC, CMP and lipid panel are the inner ring and the left rail. Each can be marked low or high; the ripple spreads from there."),
   ("Concerns each marker can represent", "addressed",
    "Derived from the catalogue's own concern tags: the 26 panel markers between them can raise <b>18 of 47</b> concerns. Calcium alone points at nine."),
   ("Click a concern for what would follow it up", "addressed",
    "Opening a concern fans its follow-up tests into an outer ring and lists them, ranked by how well sourced and how commonly ordered they are, each linking to its LOINC record."),
   ("Nothing shifts on interaction", "addressed",
    "Ring positions are computed once per window size and cached; every interaction changes colour and opacity only. All 47 concerns hold a permanent slot, so adding a personal concern moves nothing. Scroll areas use reserved gutters so a scrollbar never appears and nudges content."),
   ("Fun facts on how markers relate", "addressed",
    "<b>29 relationship notes</b>, each a verbatim quote from a MedlinePlus (NIH) page with a verify link \u2014 bilirubin coming from broken-down red cells, ALP living in both liver and bone, calcium riding on albumin, LDL being calculated rather than measured. All 29 were re-fetched and checked against their source pages: none altered, none missing."),
   ("Personal concern layer", "addressed",
    "The 29 concerns the annual panel cannot reach are addable as a second layer. Adding one that no panel marker touches says so plainly: <i>nothing in your routine bloodwork would reveal it</i>."),
   ("Missing data as clinical information", "addressed",
    "Marking one marker abnormal surfaces how many related tests sit outside the panel and have never been ordered. Across all 18 reachable concerns that is <b>3,399</b> tests."),
   ("A confirmed diagnostic sequence", "partial",
    "The follow-up lists are markers <b>tagged to a concern</b> in the catalogue, ranked \u2014 not a verified screen-then-confirm path. Only the 29 sourced notes and the 11 hand-authored conditions carry real sequencing. The panel says so rather than implying more."),
   ("Marker-to-marker network beyond the 29", "open",
    "Still blocked on the relationship layer from [[F1]]: 6 of 6,192 markers carry a cross-family link. The 29 notes are hand-curated, not a data model \u2014 they cover the annual panel and stop there."),
  ],
  "open": "The 29 relationship notes prove the idea but do not scale: they were researched one page at a time and cover only the 26 panel markers. Turning them into the <code>sets</code> and <code>edges</code> arrays scoped in \u00a75 of <code>INDEX-REFINEMENT.md</code> is what would let the ripple run past the annual panel into the rest of the catalogue.",
 },
 {
  "id": "F6",
  "date": "2026-07-30",
  "who": "Chloe",
  "title": "Track feedback in the history panel",
  "status": "addressed",
  "versions": [],
  "quote": "summarize all the feedbacks we have so far in history page as well, track them as they come in",
  "did": [
   ("Feedback ledger added to this panel", "addressed",
    "Every piece of direction so far, quoted verbatim, with what was done and what is still open."),
   ("Cross-linked to versions", "addressed",
    "Each feedback item links to the versions that answered it; each version lists the feedback it answers."),
   ("One place to add new items", "addressed",
    "The <code>FEEDBACK</code> list at the top of <code>pipeline/build_history.py</code>. Add an entry, re-run the script."),
  ],
  "open": None,
 },
 {
  "id": "F5",
  "date": "2026-07-30",
  "who": "Chloe",
  "title": "Fix the atlas panels in place",
  "status": "addressed",
  "versions": ["v1.1"],
  "quote": "let's workshop the atlas a bit more. I'd like every panel to be fixed on screen without collapsing or expanding movements, figure out the best placement for them, overlay is good too",
  "did": [
   ("Nothing scrolls or resizes", "addressed",
    "The stage is fixed; panels are absolutely positioned and hold their dimensions. Anything that could overflow scrolls inside its own box."),
   ("Placement resolved", "addressed",
    "Map as ground plane; controls top-left where reading starts, family index filling that column, detail opposite it on the right, legend and honesty line along the bottom."),
   ("Circles never jump", "addressed",
    "Positions pack once per stage size and cache; shade toggles only re-paint. Verified by diffing every circle's coordinates across a toggle."),
   ("Overlay for drill-in", "addressed",
    "Clicking through to a family's markers fades a sheet over the map. The layout underneath never moves."),
  ],
  "open": "The gap map still scrolls — you chose to workshop one screen first. Applying the same fixed language there is the obvious follow-on.",
 },
 {
  "id": "F4",
  "date": "2026-07-30",
  "who": "Chloe",
  "title": "Be explicit about what is actually live",
  "status": "addressed",
  "versions": ["v1.0"],
  "quote": "is the atlas version live on index?",
  "did": [
   ("Status is now stated, not implied", "addressed",
    "Versions carry live / candidate / superseded and the panel colours the timeline by it. The atlas is a candidate; <code>index.html</code> is still v0.4."),
   ("Rollback commands are status-aware", "addressed",
    "A candidate shows &ldquo;promote this version&rdquo; and points its git command at <code>index-v2.html</code>, where the file actually lives at that tag. Earlier versions point at <code>index.html</code>."),
  ],
  "open": None,
 },
 {
  "id": "F3",
  "date": "2026-07-30",
  "who": "Chloe",
  "title": "Version history with previews and rollback",
  "status": "addressed",
  "versions": ["v1.0"],
  "quote": "create a history record keeping panel for all the changes we have made, in case we need to roll back to older versions, make them previewable",
  "did": [
   ("Snapshots of every milestone", "addressed",
    "Six versions plus two reference artifacts in <code>versions/</code>, byte-for-byte copies verified against their git tags."),
   ("Previewable", "addressed",
    "Each renders live in an iframe as the real interactive build, with viewport toggles and open-full."),
   ("Rollback", "addressed",
    "Copy-the-snapshot and git-tag commands per version, plus a diff command to see what would change first."),
   ("Uncommitted work rescued", "addressed",
    "The free-text symptom search was sitting in the working tree; committed as its own tagged milestone (v0.4) so that state stays recoverable."),
  ],
  "open": "<code>versions/</code> is ~17 MB and will ride along on a Vercel deploy. That makes the panel shareable by URL, which seems worth it — say the word for a <code>.vercelignore</code>.",
 },
 {
  "id": "F2",
  "date": "2026-07-30",
  "who": "Chloe",
  "title": "Build the full scope, review before swapping",
  "status": "addressed",
  "versions": ["v1.0"],
  "quote": "implement the changes … Everything including R4 atlas … New file, review then swap",
  "did": [
   ("All seven recommendations built", "addressed",
    "R1&ndash;R7 including the full atlas screen. The 6,192-row table survives one level inside it."),
   ("Delivered for review, not swapped in", "addressed",
    "<code>index-v2.html</code> sits alongside the live site so it can be compared before promotion."),
  ],
  "open": None,
 },
 {
  "id": "F1",
  "date": "2026-07-30",
  "who": "Chloe",
  "title": "An atlas of blood, not another lab viewer",
  "status": "partial",
  "versions": ["v1.0", "v1.1"],
  "quote": "What we don't have is a model of the blood system itself. We don't know what other markers surround a result, what hasn't been measured, what should be measured next, or how biomarkers relate to one another across physiology.",
  "quotes": [
   "We already have good tools for seeing individual blood tests—and simple trends over time.",
   "Imagine a map instead of a list. Every blood marker exists within networks: inflammation, immunity, kidney function, metabolism, liver health, hormones, nutrition, coagulation, cancer, infection, genetics, and more. We need the “solar system” of blood markers, not isolated planets.",
   "The most valuable information may be what's missing. Which tests have never been ordered? Which families of tests are incomplete? … Missing data is itself clinical information.",
   "This is fundamentally a decision-space design problem.",
   "More data isn't the problem. Claude Shannon taught us that information reduces uncertainty. The challenge is designing interfaces that transform more information into better decisions instead of more confusion.",
   "The issue isn't the data itself. The problem is that we haven't designed an effective way for clinicians and patients to navigate it—to surface what's important, summarize the signals, expose the gaps, and reveal the relationships.",
   "The product isn't another lab viewer. It's a decision engine.",
   "The goal isn't simply to display blood work. It's to make the invisible structure of human physiology visible enough that clinicians and patients can ask better questions, order better tests, and make better decisions.",
  ],
  "did": [
   ("A map instead of a list", "addressed",
    "The atlas screen shows all 17 families as a packed map sized by what is inside them, replacing a landing page whose only promise was 6,192 rows."),
   ("Missing data as the headline", "addressed",
    "The hero leads with <b>26 of 6,192</b> &mdash; what a routine annual panel measures against what is measurable. The stat strip shows three gaps instead of three totals."),
   ("Which families are incomplete", "addressed",
    "The gap map takes what you have had drawn and returns per-family coverage. <b>14 of 17</b> families are untouched by a standard annual panel."),
   ("The six decision questions", "partial",
    "All six are on the landing as navigation, each honestly labelled. Two work; two are prototypes; one is evidenced for three panels only; one is not built."),
   ("Which tests belong together", "partial",
    "Only the three routine panels are modelled as sets. Nothing else in the catalogue is grouped by &ldquo;ordered together&rdquo;."),
   ("How biomarkers relate across physiology", "open",
    "Not built, and deliberately not faked. Only <b>6 of 6,192</b> markers carry a link to another family, so the map draws no edges and says so."),
   ("How one abnormal finding ripples", "open",
    "Blocked on the same missing relationship layer. The one worked example (iron-deficiency anemia) is hand-authored in <code>condition-lens.html</code>."),
   ("What should be measured next", "partial",
    "Screen-then-confirm exists as a prototype for one condition, not as a general capability."),
   ("Trends over time", "open",
    "Not built. Named as not built on the landing rather than quietly omitted."),
   ("What each biomarker means, with evidence", "partial",
    "All 6,192 carry a description and a link, but only <b>216</b> are quoted from a named authority; <b>5,976</b> were AI-written from the LOINC name. The ratio is on the front door."),
  ],
  "open": "The relationship layer is the blocker for three of the points above. The fix is two small additions alongside <code>tests</code> &mdash; a <code>sets</code> array for &ldquo;these are ordered together&rdquo; and an <code>edges</code> array for reflex links like low MCV &rarr; ferritin &mdash; each carrying its own quoted or reasoned source. Scoped in §5 of <code>INDEX-REFINEMENT.md</code>. Until it exists, any marker-level ripple view would be drawing edges that are not in the data.",
 },
]

# ===========================================================================
# VERSIONS — newest first
# ===========================================================================
VERSIONS = [
 {
  "id": "v2.6",
  "file": "v2.6-facts-space.html",
  "title": "Ripple atlas \u2014 roomier relationship notes",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "candidate",
  "tag": "v2.6-facts-space",
  "gitpath": "index-v3.html",
  "answers": ["F13"],
  "summary": "\u201cHow these connect\u201d gets the larger share of the detail panel instead of a fixed 184px box, so two full quote cards are visible by default.",
  "changes": [
   "<b>Relationship notes flex</b> at 1.6 against 1 for the follow-up list, with a 264px floor \u2014 they are the substance of the panel, so they get the space.",
   "<b>24px between cards</b>, last margin removed.",
   "Follow-up list keeps a 160px floor and its expander.",
   "Re-audited: zero off-grid spacing.",
  ],
 },
 {
  "id": "v2.5",
  "file": "v2.5-detail-8px.html",
  "title": "Ripple atlas \u2014 detail panel, 8px audit",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.5-detail-8px",
  "gitpath": "index-v3.html",
  "answers": ["F12"],
  "summary": "Detail panel rebuilt on the grid: nothing clipped in the header, the explanation section never scrolls, and the follow-up list expands to the rest.",
  "changes": [
   "<b>Header</b> \u2014 16px padding on a 96px minimum, vertically centred. The subtitle is no longer cut off.",
   "<b>\u201cWhy it is on the map\u201d sizes to its content</b> and has no scrollbar.",
   "<b>Follow-ups expand</b> \u2014 top 40 carried per concern (was 8), 8 shown by default, with the true total stated.",
   "<b>Full 8px audit</b> of the stylesheet: zero off-grid padding, margin, gap or height.",
   "<code>DESIGN-RULES.md</code> added, and the design rules now head the standing-rules list here.",
   "File grew 101\u2009KB \u2192 238\u2009KB carrying the extra follow-up rows.",
  ],
  "note": "Follow-up centring still clamps for concerns in the top ~130px, where a centred block would leave the canvas.",
 },
 {
  "id": "v2.4",
  "file": "v2.4-centred-followups.html",
  "title": "Ripple atlas \u2014 centred follow-ups, 8px pill",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.4-centred-followups",
  "gitpath": "index-v3.html",
  "answers": ["F11"],
  "summary": "Follow-up tests become one block centred on the concern row that produced them, and the low/normal/high pill is rebuilt on an 8px grid with a column header.",
  "changes": [
   "<b>Follow-ups centred on their concern row</b> at a 24px pitch, with a tick on the anchor row. They were previously centred in the column, which is why they started mid-page.",
   "<b>Pill rebuilt on the 8px system</b> \u2014 24px tall, 8px padding per segment, 96px column, 32px rows. No more clipped words.",
   "<b>Non-scrolling column header</b> labels the marker column and the three toggle segments.",
   "<b>Rail widened to 320px</b> (8\u00d740) so the padded pill does not squeeze the marker names.",
   "Source badge moved off the map into the detail list and tooltip, so each follow-up is one line and the block stays short enough to centre.",
   "Verified at six window sizes: zero label overlaps, zero overflow, out-dots clear of text, 92\u201396% width and 99\u2013100% height in use.",
  ],
  "note": "Centring clamps for concerns in the top ~130px, where a centred block would run off the canvas. Unavoidable; the anchor tick keeps the relationship readable.",
 },
 {
  "id": "v2.3",
  "file": "v2.3-right-connectors.html",
  "title": "Ripple atlas \u2014 right-side connectors",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.3-right-connectors",
  "gitpath": "index-v3.html",
  "answers": ["F10"],
  "summary": "Concern rows gain a second connector dot on their right edge, and the follow-up edges leave from there instead of sweeping back across the label text.",
  "changes": [
   "<b>47 right-hand connector dots</b>, one per concern row, at the right edge of the column.",
   "<b>Follow-up edges originate at the out-dot</b> rather than the left-hand dot, so no curve crosses a label.",
   "The out-dot is quiet grey until its row is the one feeding the third column, then warm and filled.",
   "Marker-count chip moved inboard to clear the new dot; label clip widths re-measured.",
   "Verified at six window sizes: zero label overlaps, zero overflow, out-dots clear of all text.",
  ],
  "note": "Only the concern column changed. Markers already had their dot on the outgoing side, and follow-up tests already had theirs on the incoming side.",
 },
 {
  "id": "v2.2",
  "file": "v2.2-column-atlas.html",
  "title": "Ripple atlas \u2014 three columns",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.2-column-atlas",
  "gitpath": "index-v3.html",
  "answers": ["F9"],
  "summary": "Static, deterministic, and dense: panel markers, concerns and follow-up tests as three fixed columns filling the whole canvas. No physics, no drift, no animation.",
  "changes": [
   "<b>Force simulation deleted.</b> Layout is a pure function of state and window size.",
   "<b>Three fixed columns</b> \u2014 26 panel markers grouped by CBC / CMP / lipid, all 47 concerns, and the follow-up tests for whichever concern is open.",
   "<b>Every row is labelled.</b> Full marker names, full concern names, no culling.",
   "<b>Barycentre ordering</b> puts each concern beside the markers that point at it, so edges run flat rather than crossing.",
   "<b>A drawn divider</b> separates the 18 concerns the annual panel can reach from the 29 it cannot.",
   "<b>Type scales with row height</b> and clips to its column: zero label overlaps and zero overflow at 1200\u00d7700 through 2560\u00d71400.",
   "Space used: 99\u2013100% of the height, 91\u201396% of the width.",
  ],
  "note": "Supersedes both v2.0 (fixed rings) and v2.1 (force layout). The rail, detail panel and the 29 sourced relationship notes are unchanged.",
 },
 {
  "id": "v2.1",
  "file": "v2.1-organic-ripple.html",
  "title": "Ripple atlas \u2014 organic layout",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.1-organic-ripple",
  "gitpath": "index-v3.html",
  "answers": ["F8"],
  "summary": "The ripple map stops being a fixed ring and becomes a live force simulation: nodes float, live concerns pull inward, dormant ones drift to the edge, and labels are placed only where they fit.",
  "changes": [
   "<b>Force simulation replaces the fixed rings.</b> A radial band per role, concerns sprung toward the markers that implicate them, universal repulsion, hard collision correction, and a boundary that keeps every node out of the panels.",
   "<b>Live concerns come forward, dormant ones recede.</b> The 47 concerns no longer each hold a permanent ring slot \u2014 the ones in play grow and move inward where there is room to label them.",
   "<b>Greedy label placement.</b> Labels are sorted by importance and take the first of four candidate positions that collides with nothing. Zero label overlaps at 1200\u00d7700 through 1920\u00d71080, in every interaction state.",
   "<b>Elliptical bands</b> so the layout fills a wide rectangle instead of inscribing a circle in it.",
   "<b>Ambient drift</b> \u2014 per-node phase, slow breathing motion, disabled under <code>prefers-reduced-motion</code>.",
   "<b>Flowing dash on live edges</b> so the ripple visibly travels outward from a marker you flag.",
   "Node overlaps: zero once settled, at every size tested.",
  ],
  "note": "Motion is confined to the map canvas. The rails, detail slots and scroll gutters stay fixed, so this does not undo the no-shift guarantee from v2.0.",
 },
 {
  "id": "v2.0",
  "file": "v2.0-ripple-atlas.html",
  "title": "Ripple atlas",
  "date": "2026-07-31",
  "source": "index-v3.html",
  "status": "superseded",
  "tag": "v2.0-ripple-atlas",
  "gitpath": "index-v3.html",
  "answers": ["F7"],
  "summary": "A different route into the atlas: start from the 26 markers of a routine annual panel, mark what came back abnormal, and watch the ripple spread into concerns and the tests that would follow them up.",
  "changes": [
   "<b>Three concentric rings.</b> Inner: the 26 annual-panel markers, grouped by CBC / CMP / lipid. Middle: all 47 concerns, each holding a permanent slot. Outer: the follow-up tests for whichever concern is open.",
   "<b>Mark low or high</b> on any panel marker and the concerns it can represent light up, with edges coloured by direction.",
   "<b>29 sourced relationship notes</b> \u2014 every one a verbatim MedlinePlus (NIH) quote with a verify link, re-checked against the source pages after authoring.",
   "<b>Personal concern layer.</b> The 29 concerns a routine panel cannot reach can be added by hand; one that no panel marker touches says so outright.",
   "<b>Nothing moves.</b> Ring geometry is computed once per window size and cached; interactions change colour and opacity only. Scroll areas reserve their gutters. Verified by diffing every circle coordinate across marking, selecting and adding.",
   "<b>Marker radius derived from the ring chord</b>, so the 26 inner circles cannot overlap at any window size. Checked at 1200\u00d7700 through 1920\u00d71080.",
   "95 KB standalone \u2014 no 6,192-row table, so it loads instantly.",
  ],
  "note": "This is an alternative to the v1.1 family atlas, not a replacement. v1.1 maps the whole catalogue by family; v2.0 starts from what you have actually had done. Both are candidates.",
 },
 {
  "id": "v1.1",
  "file": "v1.1-atlas-cockpit.html",
  "title": "Atlas cockpit — fixed panels",
  "date": "2026-07-30",
  "source": "index-v2.html",
  "status": "candidate",
  "tag": "v1.1-atlas-cockpit",
  "gitpath": "index-v2.html",
  "answers": ["F5"],
  "summary": "The atlas stops being a scrolling page and becomes a fixed cockpit: the map fills the viewport, everything else floats above it, nothing ever reflows.",
  "changes": [
   "<b>Nothing scrolls or resizes.</b> The stage is fixed; panels are absolutely positioned and hold their dimensions. Anything that could overflow scrolls inside its own box instead of growing.",
   "<b>Map is the ground plane.</b> It fills the viewport behind four floating glass panels — controls and family index on the left, detail on the right, legend and the honesty line along the bottom.",
   "<b>Circles never jump.</b> Positions are packed once per stage size and cached; toggling shade or re-ordering the index only re-paints colour. Verified by diffing circle coordinates across a shade toggle.",
   "<b>Packing is area-conserving</b> — circles scale to fill ~46% of whatever space the panels leave, so the map uses the room it has at any window size. Panel footprints are measured, not guessed, so no circle hides under a panel.",
   "<b>Detail panel is always mounted</b> at a fixed size. With nothing selected it shows the whole-atlas summary; selecting a family swaps the content without changing the box.",
   "<b>Drill-in is an overlay sheet</b> that fades over the map — every marker in the family, filterable, each linking to its LOINC record. Esc or the scrim closes it.",
   "Index and map cross-highlight on hover; clicking either selects, clicking again deselects.",
   "<b>No dimming of unselected families.</b> The shape of what is unmeasured is the point of the map, so it stays readable while you inspect one family.",
  ],
  "note": "The family-card grid from v1.0 is gone — the index rail and detail panel replace it. Landing and gap map are unchanged.",
 },
 {
  "id": "v1.0",
  "file": "v1.0-atlas-rebuild.html",
  "title": "Atlas rebuild",
  "date": "2026-07-30",
  "source": "index-v2.html",
  "status": "superseded",
  "tag": "v1.0-atlas",
  "gitpath": "index-v2.html",
  "answers": ["F1", "F2", "F3", "F4"],
  "summary": "Landing reframed from a navigation question into a claim, plus two new screens: a gap map and a family atlas.",
  "changes": [
   "<b>Hero states the thesis.</b> “Where do you want to start?” becomes “There are 6,192 things that can be measured in your blood. A routine annual checkup measures 26.”",
   "<b>Stat strip shows gaps, not totals.</b> The volume pair (6,192 tests · 17 body systems) is replaced by 26 of 6,192 in a routine panel, 1,602 markers no symptom reaches, and 4 of 17 families with no quoted source.",
   "<b>New gap map</b> (<code>#cxGaps</code>) — mark the panels you’ve had, search in individual markers, see per-family coverage. Persists to <code>localStorage</code>.",
   "<b>New family atlas</b> (<code>#cxAtlas</code>) — 17 family cards, shade by routine-panel or source coverage, sort by size / least covered / A–Z.",
   "<b>Six-question spine</b> on the landing, each labelled built / prototype / partial / not built.",
   "<b>Family map generated from the payload</b> by deterministic circle packing. No edges drawn, because only 6 of 6,192 markers carry a link to another family.",
   "<b>Honesty band</b> — 216 quoted entries vs 5,976 AI-written, with source names read out of the data.",
   "Fixed two bugs found in testing: <code>[].slice.call()</code> on a <code>Set</code> returns empty, which had silently broken the added-markers list and localStorage persistence.",
  ],
  "note": "Every figure is computed from the payload at load, so the copy cannot drift from the dataset. Regenerate with <code>pipeline/build_v2.py</code>.",
 },
 {
  "id": "v0.4",
  "file": "v0.4-symptom-search.html",
  "title": "Free-text symptom search",
  "date": "2026-07-30",
  "source": "index.html (working tree)",
  "status": "live",
  "tag": "v0.4-symptom-search",
  "answers": [],
  "diff": "196 added, 18 removed",
  "summary": "The last state of the original dashboard before the atlas rebuild. This is the roll-back target if the atlas goes wrong.",
  "changes": [
   "Free-text search on the condition explorer home (<code>cxFeelSearch</code>) with fuzzy matching into concern chips.",
   "“Search all tests” escape hatch from the search results into the table view.",
   "Feedback link added to the dashboard header.",
   "Blood-fill animation on the landing figure retuned (<code>cxrise</code> 120px → 185px).",
  ],
  "note": "These edits were uncommitted when the atlas work began; committed as their own milestone so this exact state stays recoverable.",
 },
 {
  "id": "v0.3",
  "file": "v0.3-polished-landing.html",
  "title": "Polished landing and table toolbar",
  "date": "2026-07-29",
  "ref": "2f8f5ec",
  "source": "commit 2f8f5ec",
  "tag": "v0.3-polish",
  "answers": [],
  "diff": "250 added, 25 removed",
  "summary": "Visual pass on the two-door landing and usability work on the all-tests table.",
  "changes": [
   "Landing figure with the blood-fill mask, animated leader lines to each route card, and live card stats read from the dataset.",
   "Per-system mini bar chart on the “Explore all tests” card.",
   "Table toolbar: expand all, collapse all, back to top, and a sticky toolbar dock.",
   "Rollup system bar with legend in the dashboard header.",
  ],
 },
 {
  "id": "v0.2",
  "file": "v0.2-condition-explorer.html",
  "title": "Condition explorer prototype",
  "date": "2026-07-23",
  "ref": "1f7acac",
  "source": "commit 1f7acac",
  "tag": "v0.2-condition-explorer",
  "answers": [],
  "diff": "3,595 added, 81 removed",
  "summary": "The biggest single change in the project's history: conditions become a first-class object sitting between symptoms and tests.",
  "changes": [
   "Route landing (<code>#cxRoute</code>) with two doors — start from how you feel, or explore all tests.",
   "Condition explorer (<code>#cxApp</code>): symptom → candidate conditions → condition lens.",
   "Condition lens with ripple diagram, “have you had this?” checklist, path-to-diagnosis track and a locked miniDx card.",
   "All-tests table view with name / system / source filters.",
   "Added <code>condition-lens.html</code>, <code>IMPROVEMENT-PLAN.md</code> and the <code>pipeline/</code> source files.",
  ],
  "note": "This is the version <code>IMPROVEMENT-PLAN.md</code> was written against.",
 },
 {
  "id": "v0.1",
  "file": "v0.1-initial-dashboard.html",
  "title": "Initial dashboard",
  "date": "2026-07-22",
  "ref": "786bfc5",
  "source": "commit 786bfc5",
  "tag": "v0.1-initial",
  "answers": [],
  "diff": "1,024 added",
  "summary": "The original concern-in, test-list-out tool. No conditions, no landing page, no table view.",
  "changes": [
   "6,192-test catalogue with the concern picker and age / sex / life-stage / medication filters.",
   "Rollup stat strip and callouts.",
   "“Worth asking your doctor about” ranking, and annual-panel coverage against what sits outside it.",
   "Source-quoted vs AI-generated badges throughout.",
  ],
 },
]

REFS = [
 {
  "id": "ref-wireframe",
  "file": "ref-atlas-wireframe.html",
  "title": "Atlas landing wireframe (annotated)",
  "date": "2026-07-29",
  "summary": "The annotated mockup v1.0 was built from. Each block carries a margin note explaining what changed and why. Read alongside INDEX-REFINEMENT.md.",
 },
 {
  "id": "ref-lens",
  "file": "ref-condition-lens.html",
  "title": "Condition lens — iron-deficiency anemia",
  "date": "2026-07-23",
  "summary": "Standalone, hand-authored prototype of one condition worked end to end: ripple, coverage, path to diagnosis, miniDx. The reference build the explorer was modelled on.",
 },
]

# ===========================================================================
def fsize(p):
    try:
        return round(os.path.getsize(p) / 1048576.0, 2)
    except OSError:
        return None

for v in VERSIONS + REFS:
    v["mb"] = fsize(os.path.join(ROOT, "versions", v["file"]))
    if v["mb"] is None:
        raise SystemExit("missing snapshot: versions/" + v["file"])

# resolve feedback -> versions from the versions' own "answers", so the two
# lists cannot disagree
for f in FEEDBACK:
    linked = [v["id"] for v in VERSIONS if f["id"] in v.get("answers", [])]
    f["versions"] = sorted(set(f.get("versions", []) + linked), reverse=True)

manifest = {
    "generated": subprocess.run(["date", "-u", "+%Y-%m-%dT%H:%M:%SZ"],
                                capture_output=True, text=True).stdout.strip(),
    "live": "index.html",
    "constraints": CONSTRAINTS,
    "feedback": FEEDBACK,
    "versions": VERSIONS,
    "references": REFS,
}
io.open(os.path.join(ROOT, "versions", "manifest.json"), "w", encoding="utf8").write(
    json.dumps(manifest, indent=1, ensure_ascii=False))

TOTAL_MB = round(sum(v["mb"] for v in VERSIONS + REFS), 1)
COUNTS = {k: sum(1 for f in FEEDBACK if f["status"] == k)
          for k in ("addressed", "partial", "open")}

HTML = io.open(os.path.join(ROOT, "pipeline", "history_template.html"),
               encoding="utf8").read()
HTML = HTML.replace("__MANIFEST__", json.dumps(manifest, ensure_ascii=False))
HTML = HTML.replace("__TOTAL__", str(TOTAL_MB))
io.open(os.path.join(ROOT, "history.html"), "w", encoding="utf8").write(HTML)

print("versions/manifest.json  %d feedback, %d versions, %d references"
      % (len(FEEDBACK), len(VERSIONS), len(REFS)))
print("history.html            %.1f KB, %.1f MB of snapshots indexed"
      % (len(HTML) / 1024.0, TOTAL_MB))
print("feedback                %(addressed)d addressed, %(partial)d partial, %(open)d open" % COUNTS)
for f in FEEDBACK:
    print("   %-3s %-9s %-44s -> %s" % (f["id"], f["status"], f["title"],
                                        ", ".join(f["versions"]) or "—"))
